= FACHBEREICHSORDNUNG DER MATHEMATISCHNATURWISSENSCHAFTLICHEN FAKULTÄT

== DER HEINRICH-HEINE UNIVERSITÄT DÜSSELDORF VOM 7.11.2017

NOTE: Aufgrund der https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643690[§§ 2 Abs. 4 Satz 1], https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643719[26 Abs. 3] des Gesetzes über die Hochschulen des Landes NordrheinWestfalen (Hochschulgesetz- HG) vom 16. September 2014 (GV NRW S. 547) hat die Heinrich-Heine Universität Düsseldorf die folgende Ordnung erlassen:

=== § 1 Organisation
(1) Die Mathematisch-Naturwissenschaftliche Fakultät besteht aus den wissenschaftlichen Einrichtungen Biologie, Chemie, Informatik, Mathematik, Pharmazie, Physik und Psychologie.

=== § 2 Dekanin / Dekan, Prodekanin / Prodekan und Studiendekanin / Studiendekan
(1) Die Dekanin / der Dekan leitet die Mathematisch-Naturwissenschaftliche Fakultät und vertritt sie innerhalb der Heinrich-Heine-Universität Düsseldorf.

(2) Die Dekanin / der Dekan wird durch die Prodekanin / den Prodekan vertreten.

(3) Der Fakultätsrat bestellt gemäß xref:grundordnung::index.adoc#_15_fakultäten[§ 15 (2) der Grundordnung] eine Studiendekanin / einen Studiendekan, die / der mit der Wahrnehmung von Aufgaben insbesondere im Bereich der Studienorganisation und der Studienplanung beauftragt wird.

(4) Die Abwahl der Dekanin / des Dekans (https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643720[§ 27 Abs. 5 HG]) muss von mindestens acht stimmberechtigten Mitgliedern des Fakultätsrates beantragt werden; der Antrag muss eine zu wählende Dekanin / einen zu wählenden Dekan benennen, die / der sich zur Annahme der Wahl bereit erklärt hat.

=== § 3 Wissenschaftliche Einrichtungen
(1) Die Leitung einer wissenschaftlichen Einrichtung obliegt dem Vorstand.

(2) Stimmberechtigte Mitglieder des Vorstands einer wissenschaftlichen Einrichtung sind die an der wissenschaftlichen Einrichtung tätigen Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer sowie die gewählten Mitglieder aus den anderen Gruppen.

(3) Gehören dem Vorstand einer wissenschaftlichen Einrichtung bis zu sieben Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer an, wird jeweils ein Mitglied, gehören ihm acht bis vierzehn Mitglieder an, werden jeweils zwei Mitglieder, anderenfalls jeweils drei Mitglieder aus den anderen Gruppen gewählt; maßgebend ist die Zahl der Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer zum Zeitpunkt der Wahl.

(4) Die Vertreterinnen und Vertreter der Gruppe der akademischen Mitarbeiterinnen und Mitarbeiter, der Mitarbeiterinnen und Mitarbeiter in Technik und Verwaltung und der Studierenden werden nach Gruppen getrennt gewählt.

(5) Die akademischen Mitarbeiterinnen und Mitarbeiter sowie die Mitarbeiterinnen und Mitarbeiter in Technik und Verwaltung sind in der wissenschaftlichen Einrichtung wählbar und wahlberechtigt, an der sie tätig sind. Studierende sind in der wissenschaftlichen Einrichtung wählbar und wahlberechtigt, der der Studiengang zugeordnet ist, in den sie eingeschrieben sind. Ein Studiengang ist dabei derjenigen wissenschaftlichen Einrichtung mit dem größten Anteil am in der Prüfungsordnung festgelegten Lehrangebot zugeordnet. Ist eine Studierende oder ein Studierender in mehrere Studiengänge eingeschrieben, die verschiedenen wissenschaftlichen Einrichtungen zugeordnet sind, so ist er oder sie in derjenigen wissenschaftlichen Einrichtung wählbar und wahlberechtigt, die in §1 zuerst genannt ist.

(6) Die Vertreterinnen und Vertreter der Studierenden werden in den StudierendenVollversammlungen des Sommersemesters gewählt.

(7) Die akademischen Mitarbeiterinnen und Mitarbeiter und die Mitarbeiterinnen und Mitarbeiter in Technik und Verwaltung wählen ihre Vertretungen getrennt in Wahlversammlungen, die für beide Gruppen zeitlich und örtlich gemeinsam durchgeführt werden können.

(8) Die geschäftsführende Leiterin / der geschäftsführende Leiter hat die Wahlleitung, beruft die Wahlversammlungen ein und leitet sie. Die Wahlleitung kann an Mitglieder der Statusgruppen delegiert werden, die nicht selbst kandidieren. Zur Durchführung der Wahl können weitere Wahlhelfer hinzugezogen werden.

(9) Die Wahlleitung kündigt die Wahlen sowie Ort und Termin der Wahlversammlung mindestens sechs Wochen vor dem Wahltermin durch Aushang und Rundmail oder in sonst geeigneter Weise an.

(10) Wahlvorschläge können schriftlich oder per E-Mail bis zu zwei Wochen vor dem Termin der Wahlversammlung bei der Wahlleitung eingebracht werden. Die Vorgeschlagenen müssen erklären, dass sie im Fall der Wahl das Mandat annehmen. Vorgeschlagene, die in der Wahlversammlung nicht anwesend sein können, müssen der Wahlleitung ihre Bereitschaft vorab schriftlich erklären. Pro Gruppe wird eine Liste der Wahlvorschläge in geeigneter Weise, z.B. durch Aushang, veröffentlicht.

(11) Die Wahlleitung stellt sicher, dass nur Stimmberechtigte an der Wahlversammlung teilnehmen.

(12) Wahlberechtigte, die nicht an der Wahlversammlung teilnehmen können, haben die Möglichkeit zur schriftlichen Stimmabgabe. Der Wahlbrief muss dem Wahlleiter vor Beginn der Wahlversammlung zugegangen sein. Die Stimmabgabe ist nur gültig unter dem Vorbehalt der Bereitschaftserklärung der gewählten Person gemäß (11).

(13) Die Wahl erfolgt in unmittelbarer, freier und geheimer Wahl. Gewählt ist, wer die meisten gültigen Stimmen erhält. Bei Stimmengleichheit entscheidet das Los.

(14) Die Wahlleitung stellt das Wahlergebnis fest und gibt es abschließend bekannt. Über die Wahlhandlung und die Feststellung des Wahlergebnisses ist eine Wahlniederschrift zu erstellen. Das Wahlergebnis wird der Dekanin / dem Dekan mitgeteilt und auf den Webseiten der Fakultät veröffentlicht.

(15) Die Amtszeit der Mitglieder aus den Gruppen der akademischen Mitarbeiterinnen und Mitarbeiter sowie der Mitarbeiterinnen und Mitarbeiter in Technik und Verwaltung beträgt zwei Jahre. Die Amtszeit der Mitglieder aus der Gruppe der Studierenden beträgt ein Jahr.

(16) Der WE-Vorstand wählt aus seiner Mitte eine Professorin / einen Professor für eine Amtszeit von zwei Jahren zur geschäftsführenden Leiterin / zum geschäftsführenden Leiter sowie eine stellvertretende geschäftsführende Leiterin / einen stellvertretenden geschäftsführenden Leiter; sie / er vertritt die wissenschaftliche Einrichtung innerhalb der Fakultät und führt deren Geschäfte in eigener Zuständigkeit. Sie / er ist den Mitgliedern des Vorstandes gegenüber auskunfts- und rechenschaftspflichtig.

=== § 4 Studienbeirat
(1) Zur Beratung des Fakultätsrates und der Dekanin / des Dekans in Angelegenheiten der Lehre und des Studiums, insbesondere in Angelegenheiten der Studienreform, der Evaluation von Studium und Lehre sowie hinsichtlich des Erlasses oder der Änderung von Prüfungsordnungen wird vom Fakultätsrat ein Studienbeirat eingerichtet. Der Beirat kann in Selbstbefassung tätig werden.

(2) Dem Studienbeirat gehören an:

1. die Studiendekanin / der Studiendekan als Vorsitzende ohne Stimmrecht / als Vorsitzender ohne Stimmrecht,
2. für jede wissenschaftliche Einrichtung jeweils ein Mitglied aus der Gruppe der Hochschullehrerinnen und Hochschullehrer oder der Gruppe der akademischen Mitarbeiterinnen und Mitarbeiter,
3. für jede wissenschaftliche Einrichtung ein Mitglied aus der Gruppe der Studierenden.

(3) Die Mitglieder des Studienbeirates nach Absatz 2, Nr. 2 und Nr. 3 sowie jeweils deren persönliche Stellvertreter werden von den jeweiligen Vorständen der Wissenschaftlichen Einrichtungen auf Vorschlag der entsprechenden Gruppenvertreter gewählt. Die Amtszeit beträgt zwei Jahre; die Amtszeit der studentischen Mitglieder beträgt ein Jahr.

(4) Der Studienbeirat ist beschlussfähig, wenn die Mehrheit der Mitglieder anwesend ist. Der Beirat beschließt mit der Mehrheit der abgegebenen Stimmen. Bei Stimmengleichheit liegt kein Beschluss des Studienbeirats vor.

=== § 5 Inkrafttreten
Diese Fakultätsordnung tritt am Tage nach ihrer Veröffentlichung in den Amtlichen Bekanntmachungen der Heinrich-Heine-Universität Düsseldorf in Kraft.
