= Geschäftsordnung des Rates der Mathematisch-Naturwissenschaftlichen Fakultät der Heinrich-Heine-Universität Düsseldorf

== I. Wahl der Dekanin / des Dekans, Prodekanin / des Prodekans und der Studiendekanin / des Studiendekans
=== § 1
Die amtierende Dekanin /der amtierende Dekan beruft den neugewählten Fakultätsrat unter Einhaltung einer Ladungsfrist von einer Woche zu einer konstituierenden Sitzung ein, in der die Wahlen der Dekanin / des Dekans, der Prodekanin / des Prodekans und der Studiendekanin / des Studiendekans durchgeführt werden.

(1) Für die Wahl der Dekanin / des Dekans, der Prodekanin / des Prodekans und der Studiendekanin / des Studiendekans beauftragt der Fakultätsrat in der Wahlversammlung aus seiner Mitte ein Mitglied der Gruppe der Professorinnen und Professoren mit der Wahlleitung. Kandidierende Personen können die Wahlleitung nicht ausüben.

(2) Wahlvorschläge zu den Wahlen der Dekanin / des Dekans, für das Amt der Prodekanin / des Prodekans und das Amt der Studiendekanin / des Studiendekans werden in der Wahlversammlung gegenüber der Wahlleitung schriftlich oder mündlich abgegeben. Der Wahlvorschlag bedarf der Unterstützung von mindestens drei Mitgliedern des Fakultätsrates. Jedes Fakultätsratsmitglied darf in dem jeweiligen Wahlverfahren nur einen Wahlvorschlag abgeben bzw. unterstützen.

(3) Die Wahlleitung prüft die Gültigkeit der Wahlvorschläge. Die Wahlvorschläge sind zu protokollieren und zu den Unterlagen des Fakultätsrates zu nehmen.

(4) Kandidierende Personen für die Wahl zur Dekanin / zum Dekan, für das Amt der Prodekanin / des Prodekans und das Amt der Studiendekanin / des Studiendekans stellen sich einer Befragung durch den Fakultätsrat. Im Anschluss hieran werden die Wahlen in getrennten Verfahren nach Maßgabe der folgenden Vorschriften durchgeführt.

(5) Die Wahl im Fakultätsrat ist geheim. Das Wahlrecht wird durch Abgabe eines Stimmzettels ausgeübt. Briefwahl findet nicht statt. Ist dem Fakultätsrat nur eine Person zur Wahl vorgeschlagen, so ist auf dem Stimmzettel mit Ja oder Nein zu stimmen. Sind dem Fakultätsrat mehrere Personen vorgeschlagen, so hat jedes Mitglied des Fakultätsrates eine Stimme, die es durch Niederschreiben des Namens der jeweiligen kandidierenden Person abgibt. Stimmzettel, auf denen anders als mit Ja oder Nein abgestimmt wird oder die mehr als einen Namen enthalten, sind ungültig.

(6) Die Dekanin / der Dekan, die Prodekanin / der Prodekan und die Studiendekanin / der Studiendekan werden jeweils mit mehr als der Hälfte der Stimmen der stimmberechtigten Mitglieder des Fakultätsrates gewählt. Wird diese Mehrheit auch im zweiten Wahlgang nicht erreicht, so erfolgt ein neuer Vorschlag, über den in einer unter Beachtung der Ladungsfrist neu einzuberufenden Wahlversammlung abzustimmen ist.

(7) Die Gewählten sind unverzüglich zu befragen, ob sie die Wahl annehmen.

(8) Die Wahlleitung stellt das Abstimmungsergebnis fest und gibt das Wahlergebnis in der Fakultät bekannt.

== II. Abwahl der Dekanin / des Dekans, der Prodekanin / des Prodekans und der Studiendekanin / des Studiendekans

Das Verfahren zur Abwahl der Dekanin / des Dekans regelt gemäß https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643720[§ 27 Abs. 5 HG] die Fakultätsordnung.

Das Verfahren zur Abwahl der Prodekanin / des Prodekans und der Studiendekanin / des Studiendekans wird entsprechend der Abwahl der Dekanin / des Dekans vorgenommen. Hierfür muss die Abwahl der Prodekanin / des Prodekans oder die Abwahl der Studiendekanin / des Studiendekans von mindestens acht stimmberechtigten Mitgliedern des Fakultätsrates beantragt werden; der Antrag muss eine zu wählende Prodekanin / einen zu wählenden Prodekan bzw. eine zu wählende Studiendekanin / einen zu wählenden Studiendekan benennen, die / der sich zur Annahme der Wahl bereit erklärt hat.

== III. Dekanatsgeschäfte

=== § 2
Die Dekanin / der Dekan führt die Geschäfte der Fakultät. Sie / er ist den im Dekanat beschäftigten Dekanatsangehörigen unmittelbar vorgesetzt.

=== § 3
Geschäftsführung und Schriftverkehr sind aktenkundig zu machen. Die Mitglieder des Fakultätsrates und die geschäftsführenden Leiterinnen und Leiter der Wissenschaftlichen Einrichtungen haben das Recht, die Akten nach Abstimmung mit der Dekanin / dem Dekan einzusehen.

=== § 4
Die Geschäfte der Fakultät werden schriftlich im elektronischen Umlauf oder mündlich in Sitzungen des Fakultätsrates erledigt.

=== § 5
Im elektronischen Umlauf werden vorwiegend Angelegenheiten behandelt, die der Information der Fakultätsratsmitglieder dienen. Wird im elektronischen Umlaufverfahren ein Beschluss herbeigeführt, ist die absolute Mehrheit der stimmberechtigten Mitglieder des Fakultätsrates notwendig. Diese Angelegenheit ist auf der nächsten Sitzung des Fakultätsrates erneut zu behandeln, wenn die absolute Mehrheit nicht erreicht wird.

=== § 6
In den Sitzungen des Fakultätsrates werden Angelegenheiten erledigt, die eine mündliche Aussprache oder eine Beschlussfassung erfordern.

=== § 7
In Fällen, die keinen Aufschub zulassen, ist die Dekanin / der Dekan befugt, selbstständig die notwendigen Maßnahmen zu treffen; sie / er hat jedoch so bald wie möglich dem Fakultätsrat darüber Bericht zu erstatten (https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643702[12 (4) HG]).

== IV. Die Fakultätsratssitzung

=== § 8
(1) An den Fakultätsratssitzungen nehmen die Mitglieder des Fakultätsrates gemäß xref:grundordnung::index.adoc#_15_fakultäten[§ 15 (3) und (5) der Grundordnung] teil. Darüber hinaus können beratend die der Mathematisch-Naturwissenschaftlichen Fakultät angehörenden Senatsmitglieder, sowie je eine Vertreterin / ein Vertreter der akademischen Mitarbeiterinnen und Mitarbeiter und der Studierenden aus den Fächern an den Sitzungen teilnehmen, die durch die Wahl nicht direkt vertreten sind. Diese werden nach der Rangfolge im Wahlergebnis der Wahlen zum Fakultätsrat ermittelt. Bei der Behandlung von Punkten nach <<_21,§ 21 Abs. 3 dieser Geschäftsordnung>> sind alle Professorinnen und Professoren bzw. alle Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer teilnahmeberechtigt.

(2) Die Fakultätsratssitzung wird von der Dekanin / dem Dekan oder einem / einer Stellvertreter/in geleitet.

(3) Die Dekanin / der Dekan lädt zu den ordentlichen Fakultätsratssitzungen eine Woche vorher schriftlich unter Angabe der Tagesordnung ein. Die Tagesordnung wird den unter <<_8,§ 8 (1)>> genannten Personen übersandt. Sitzungen des Fakultätsrates finden in der Regel nur in der Vorlesungszeit statt.

(4) Die Dekanin / der Dekan ist verpflichtet, auf Antrag von mindestens vier stimmberechtigten Mitgliedern des Fakultätsrates eine Sitzung des Rates einzuberufen. Der Antrag ist schriftlich zu stellen und zu begründen.

(5) Die Dekanin / der Dekan ist ermächtigt, zu einzelnen Tagesordnungspunkten Referentinnen / Referenten einzuladen.

(6) Die um die nicht öffentlich zu behandelnden Punkte gekürzte Tagesordnung wird rechtzeitig vor der Fakultätsratssitzung fakultätsöffentlich bekannt gemacht.

=== § 9
(1) Die Dekanin / der Dekan stellt die Tagesordnung auf.

(2) Anträge zur Tagesordnung müssen spätestens elf Tage vor der Sitzung unter Beifügung der Unterlagen der Dekanin / dem Dekan schriftlich vorliegen.

(3) Nachträglich können Angelegenheiten nur ausnahmsweise auf die Tagesordnung gesetzt werden, wenn die Mehrheit der anwesenden Ratsmitglieder zustimmt. Beschlüsse können zu solchen nachträglichen Tagesordnungspunkten nur dann gefasst werden, wenn keines der anwesenden Mitglieder des Rates widerspricht. Das Gleiche gilt für Beschlüsse, die unter dem Tagesordnungspunkt „Verschiedenes“ gefasst werden sollen.

=== § 10
Die in <<_8,§ 8 (1) Satz 1>> genannten Personen sind verpflichtet, an den Sitzungen des Fakultätsrates teilzunehmen. Eine Verhinderung ist unter Angabe des Grundes vor der Sitzung der Dekanin / dem Dekan anzuzeigen.

=== § 11
(1) Der Fakultätsrat ist beschlussfähig, wenn mehr als die Hälfte der bezüglich des jeweiligen Gegenstandes stimmberechtigten Mitglieder des Fakultätsrates anwesend ist. Nach Eröffnung der Sitzung wird diese Beschlussfähigkeit überprüft, später nur nach Unterbrechung der Sitzung oder auf Antrag. Die Dekanin / der Dekan kann die Beschlussfähigkeit jederzeit überprüfen. Wahlen und Abstimmungen, die dem Antrag auf Überprüfung der Beschlussfähigkeit bzw. der Überprüfung durch die Dekanin / den Dekan vorangehen, sind gültig. Während einer Wahl oder Abstimmung ist die Überprüfung der Beschlussfähigkeit nicht statthaft.

(2) Über einen wegen Beschlussunfähigkeit vertagten Gegenstand kann auf der nächsten ordnungsgemäß einberufenen Sitzung ein gültiger Beschluss gefasst werden, auch wenn weniger als die zur Beschlussfähigkeit notwendige Zahl von Mitgliedern teilnimmt. Auf diese Regelung muss in der Einladung, die solche Punkte enthält, ausdrücklich hingewiesen werden.

=== §12
Unter der Leitung der Dekanin / des Dekans werden die Punkte der Tagesordnung abschließend behandelt. Ist eine abschließende Behandlung nicht möglich, so ist eine Vertagung oder eine Überweisung an einen Ausschuss oder eine Kommission zu beschließen.

=== § 13
(1) Die nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643721[§ 28 (2) und (3) HG], nach xref:grundordnung::index.adoc#_15_fakultäten[§ 15 (3) der Grundordnung] und nach <<_8,§ 8 (1) dieser Geschäftsordnung>> jeweils Teilnahmeberechtigten haben das Recht, sich zu den entsprechenden Tagesordnungspunkten zu äußern. Die Diskussionsbemerkungen sind knapp und sachlich vorzutragen. Die Dekanin / der Dekan hat das Recht, bei unsachlichen oder weitschweifigen Ausführungen die Rednerin / den Redner zu unterbrechen, zur Sachlichkeit zu ermahnen und ihr / ihm mit Zustimmung des Fakultätsrates das Wort zu entziehen.

(2) Wortmeldungen werden von der Dekanin / dem Dekan der Reihe nach berücksichtigt. Bei Streitigkeiten um die Reihenfolge ist von der Versammlung eine Rednerliste zu beschließen.

(3) Zur sachlichen Richtigstellung oder zur direkten Erwiderung erteilt die Dekanin / der Dekan auch außerhalb der Reihenfolge das Wort.

(4) Zur Geschäftsordnung muss das Wort außerhalb der Reihenfolge der Wortmeldungen erteilt werden.

(5) Jedes Mitglied kann den Antrag auf Schluss der Debatte oder auf Schluss der Rednerliste stellen, der begründet werden muss. Nach einer eventuellen Gegenrede ist über diesen Antrag sofort abzustimmen; wird dem Antrag auf Schluss der Rednerliste stattgegeben, so kann eine weitere Wortmeldung zu diesem Verhandlungspunkt nicht mehr angenommen werden.

=== § 14
(1) Wird eine Sitzung des Fakultätsrates durch das Verhalten von Personen aus der Öffentlichkeit gestört und bleibt eine Abmahnung erfolglos, so kann die Dekanin / der Dekan die Störer ausschließen.

(2) Wird dem Ausschluss nicht Folge geleistet, so kann die Dekanin / der Dekan die Sitzung unterbrechen oder schließen.

=== § 15
Nach Erledigung der Tagesordnung erklärt die Dekanin / der Dekan die Sitzung des Fakultätsrates für geschlossen.

=== § 16
(1) Über die Verhandlungen des Fakultätsrates führt die Geschäftsführerin / der Geschäftsführer der Fakultät ein Protokoll, das der Dekanin / dem Dekan und anschließend den in <<_8,§ 8 (1) Satz 1 und 2>> genannten Personen vor der nächsten regulären Ratssitzung zur Kenntnis zu bringen ist. Wenn gegen Form und Inhalt des Protokolls kein Einwand erhoben wird, wird es von der Dekanin / dem Dekan und der Schriftführerin / dem Schriftführer unterzeichnet und zu den Akten genommen.

(2) Jedes Mitglied des Fakultätsrates kann verlangen, dass seine von einem Beschluss abweichende Meinung als Sondervotum in das Protokoll aufgenommen wird (https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643702[§ 12 (3) HG]).

=== § 17
Bei Angelegenheiten, deren Vertraulichkeit der Fakultätsrat mit einfacher Mehrheit beschließt, und bei Personalangelegenheiten sind alle Teilnahmeberechtigten zur Verschwiegenheit über den Gang der Beratungen gegenüber jedermann verpflichtet. Über die Ergebnisse der Beratungen informieren die gewählten Gruppenvertreterinnen / Gruppenvertreter die Mitglieder ihrer Gruppe nach eigenem Ermessen, sofern nicht auch die Vertraulichkeit der Beratungsergebnisse beschlossen worden ist (https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643698[§ 10 (3) HG]).

=== § 18
An Verhandlungen und Abstimmungen, die ein Mitglied des Fakultätsrates oder seine Angehörigen betreffen, nimmt dieses nicht teil. Handelt es sich dabei um die Dekanin / den Dekan, so leitet ein / eine Stellvertreter/in die Sitzung.

== V. Abstimmungsordnung
=== § 19
(1) Abstimmungen finden grundsätzlich im unmittelbaren Anschluss an die Beratung des Tagesordnungspunktes statt, wenn keine Wortmeldungen mehr vorliegen oder wenn der Antrag auf Schluss der Debatte bzw. Rednerliste angenommen und die Rednerliste abgeschlossen ist.

(2) Über jeden Antrag ist einzeln abzustimmen. Bei mehreren Anträgen wird über den weitestgehenden Antrag zuerst abgestimmt. Im Zweifel entscheidet die Dekanin / der Dekan.

=== § 20
(1) Abstimmungen, bei denen kein anderes Verfahren vorgeschrieben ist, erfolgen durch Handzeichen.

(2) Auf Verlangen eines Mitgliedes muss eine Abstimmung schriftlich und geheim vorgenommen werden.

(3) Abstimmungen in persönlichen Angelegenheiten erfolgen grundsätzlich schriftlich und geheim.

=== § 21
(1) Bei Abstimmungen entscheidet, wenn nicht eine qualifizierte Mehrheit vorgeschrieben ist, die Mehrheit der Stimmen der bezüglich des jeweiligen Gegenstandes nach <<_11,§ 11>>

(2) HG anwesenden Stimmberechtigten. Bei Stimmengleichheit ist der Antrag abgelehnt. Stimmenthaltungen und ungültige Stimmen zählen nicht mit bei der Berechnung der Mehrheit.

(2) Wenn eine qualifizierte Mehrheit vorgeschrieben ist, so ist die Anzahl der abgegebenen Ja-Stimmen im Verhältnis zur Zahl der anwesenden Stimmberechtigten entscheidend. Die Bestimmungen des https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643699[§ 11 (3) HG] bleiben davon unberührt.

(3) Bei der Beschlussfassung über Berufungsvorschläge von Professorinnen oder Professoren sind alle Professorinnen und Professoren innerhalb der Gruppe der Hochschullehrerinnen und Hochschullehrer der Fakultät ohne Stimmrecht teilnahmeberechtigt. Gleiches gilt bei der Beratung von sonstigen Berufungsvorschlägen, Habilitationen und Habilitations- und Promotionsordnungen für alle Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer der Fakultät (https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643721[§ 28 (5) HG]). Sie werden von den Leiterinnen und Leitern der Wissenschaftlichen Einrichtungen über die entsprechenden Tagesordnungspunkte informiert.

(4) In Personal- und Prüfungsangelegenheiten ist Stimmenthaltung unzulässig.

=== § 22
(1) Einmal gefasste Beschlüsse können nur revidiert werden, wenn unter Vorlage des alten Beschlusses über den beschlossenen Sachverhalt neue und wesentliche Tatsachen und Gesichtspunkte bekanntgemacht werden.

(2) Was neu und wesentlich ist, entscheidet im Zweifel ein ad hoc herbeizuführender Beschluss, der mit Zweidrittelmehrheit der anwesenden Stimmberechtigten gefasst werden muss.

== VI. Kommissionen und Ausschüsse
=== § 23
(1) Der Fakultätsrat kann Ausschüsse und Kommissionen bilden und deren Mitglieder in offener Abstimmung wählen.

(2) Als ständige Kommission wird eingesetzt:

a. Kommission der WE-Leiterinnen und WE-Leiter, ergänzt durch je eine Sprecherin oder einen Sprecher der nichtwissenschaftlichen und akademischen Mitarbeiterinnen und Mitarbeiter und Studierenden aus dem Fakultätsrat.

=== § 24
In den Fakultätskommissionen führt die Dekanin / der Dekan den Vorsitz. Als Federführende / Federführender einer Kommission kann eines der Mitglieder gewählt oder von der Dekanin / dem Dekan bestimmt werden.

=== § 25
Auf die Tätigkeit der Fakultätskommissionen und –ausschüsse findet diese Geschäftsordnung sinngemäß Anwendung.

=== § 26
Die Sitzungen der Kommission nach <<_23,§ 23 (2)>> finden regelmäßig vor den Fakultätsratssitzungen statt, darüber hinaus zu wichtigen Anlässen (z. B. Personal, Haushalt). Die Mitglieder beraten die Dekanin / den Dekan und informieren die wissenschaftlichen Einrichtungen bzw. die an den Sitzungen des Fakultätsrates Teilnahmeberechtigten ihrer Gruppe.

== VII. Änderung der Geschäftsordnung
=== § 27
Für eine Änderung der Geschäftsordnung ist eine Zweidrittelmehrheit der stimmberechtigten Mitglieder des Fakultätsrates erforderlich.

== VIII. Gültigkeitsklausel
Sollten einzelne Bestimmungen dieser Geschäftsordnung unwirksam sein oder werden, so wird dadurch die Gültigkeit der übrigen Bestimmungen nicht berührt. Der Fakultätsrat ist verpflichtet, ungültige Bestimmungen durch rechtswirksame Regelungen zu ersetzen, die dem mit den ungültigen Bestimmungen angestrebten Zweck gerecht werden. Diese Ordnung tritt aufgrund des Beschlusses des Fakultätsrates der MathematischNaturwissenschaftlichen Fakultät vom 26. Januar 2016 sofort in Kraft.