= Grundordnung

== der Heinrich-Heine-Universität Düsseldorf vom 17.03.2015

NOTE: Aufgrund des https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643690[§ 2 Abs. 4 Satz 1 des Gesetzes über die Hochschulen des Landes Nordrhein Westfalen (Hochschulgesetz – HG)] vom 16. September 2014 (GV. NRW. S. 574) hat die Heinrich-Heine-Universität Düsseldorf folgende Grundordnung erlassen:

=== § 1 Rechtsstellung und Aufgaben
(1) Die Heinrich-Heine-Universität Düsseldorf ist eine Körperschaft des öffentlichen Rechts und hat das Recht zur Selbstverwaltung im Rahmen des Hochschulgesetzes und der übrigen Gesetze. Sie kann ein eigenes Wappen und ein eigenes Siegel führen.

(2) Die Heinrich-Heine-Universität Düsseldorf dient im Zusammenwirken ihrer Mitglieder der Wissenschaft in Forschung, Lehre und Studium und fördert im Geiste ihres Namenspatrons eine Kultur der Toleranz, Weltoffenheit und Freiheit. Ziel der Forschung ist die Gewinnung wissenschaftlicher Erkenntnisse sowie die wissenschaftliche Grundlegung und Weiterentwicklung von Lehre und Studium. Das Studium soll Methoden, fachliche Kenntnisse und die Fähigkeit zu wissenschaftlicher und beruflicher Arbeit sowie einer kritischen Einordnung wissenschaftlicher Erkenntnisse vermitteln.

(3) Die Heinrich-Heine-Universität Düsseldorf wahrt die Freiheit von Forschung, Lehre und Studium und orientiert sich an dem Leitbild der Autonomie der Universität. Sie wirkt an der Erhaltung und Weiterentwicklung des demokratischen und sozialen Rechtsstaates und seiner Werte mit. Forschung, Lehre und Studium an der Heinrich-Heine-Universität Düsseldorf sind friedlichen Zielen verpflichtet, sie tragen zur Völkerverständigung bei und erfolgen in der Verantwortung für eine nachhaltige Entwicklung der natürlichen und sozialen Lebensgrundlagen.

(4) Grundvoraussetzung für wissenschaftliche Arbeit und ein akademisches Studium ist die Redlichkeit der Wissenschaftlerinnen und Wissenschaftler und der Studierenden. Die Sicherung wissenschaftlicher Qualitätsstandards ist deshalb ein wesentliches Anliegen der Heinrich-Heine-Universität Düsseldorf. In Forschung, Lehre und Studium werden die Grundsätze guter wissenschaftlicher Praxis vermittelt und gelebt. Näheres zu der Umsetzung der Grundsätze guter wissenschaftlicher Praxis, den verantwortlichen Organen und den Verfahren regelt die Universität durch eine Ordnung.

(5) Die Heinrich-Heine-Universität Düsseldorf fördert bei der Wahrnehmung ihrer Aufgaben die Gleichberechtigung von Frauen und Männern in der Hochschule. Sie beachtet bei allen Vorschlägen und Entscheidungen die geschlechtsspezifischen Auswirkungen (Gender Mainstreaming), trägt der Vielfalt ihrer Mitglieder (Diversity Management) angemessen Rechnung und wirkt auf die Beseitigung bestehender Nachteile hin.

(6) Die Verwirklichung guter Beschäftigungsbedingungen ist ein zentrales Ziel der HeinrichHeine-Universität Düsseldorf. Sie fördert die Weiterbildung ihres Personals und nimmt Aufgaben der Berufsbildung nach dem Berufsbildungsgesetz wahr.

(7) Die Heinrich-Heine-Universität Düsseldorf wirkt an der sozialen Förderung der Studierenden mit. Sie trägt Sorge dafür, dass Studierende und Beschäftigte mit Behinderung oder chronischer Erkrankung nicht benachteiligt und deren besondere Bedürfnisse mit angemessenen Vorkehrungen berücksichtigt werden. Die Universität unterstützt Studierende und Beschäftigte mit Verantwortung für nahe Angehörige mit Pflege- oder Unterstützungsbedarf. Sie fördert die Vereinbarkeit von Studium, Beruf und Familie, insbesondere durch Betreuungsangebote für Kinder.

=== § 2 Mitglieder und Angehörige
(1) Die Universität hat Mitglieder und Angehörige nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643697[§ 9 HG]. Ihre ehemaligen Studierenden und ihre ehemaligen Beschäftigten erhalten den Status einer oder eines Angehörigen, soweit sie nicht den Mitgliederstatus behalten, wieder erworben haben oder der Verleihung des Status widersprechen. Zuständiges Organ für die Einräumung der mitgliedschaftlichen Rechtsstellung einer Professorin oder eines Professors nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643697[§ 9 Abs. 2 HG] ist das Rektorat.

(2) Bei der Beurlaubung von Professorinnen und Professoren an auf der Grundlage des https://www.gesetze-im-internet.de/gg/art_91b.html[Artikels 91b des Grundgesetzes] gemeinsam von Bund und Ländern geförderten außeruniversitären Forschungseinrichtungen bleibt neben dem Mitgliedschaftsrecht (https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643698[§ 10 Abs. 1 HG]) vorbehaltlich einer entsprechenden Feststellung des Rektorats das Recht zur Teilnahme an Wahlen und Abstimmungen bestehen. Angehörige einer außeruniversitären Forschungseinrichtung im Sinne des Satzes 1, die dort hauptberuflich tätig sind, können die Mitgliedschaft zur Universität erwerben, sofern sie im Rahmen einer Kooperationsvereinbarung Aufgaben der Universität wahrnehmen und die Einstellungsvoraussetzungen erfüllen, die für das Personal jener Mitgliedergruppe gelten, der sie zugeordnet werden sollen. Die Mitgliedschaft bedarf im Einzelfall der Feststellung durch das Rektorat.

(3) Honorarprofessorinnen und Honorarprofessoren sowie außerplanmäßige Professorinnen und Professoren haben nach Maßgabe der Ordnungen der Fakultäten das Recht und die Pflicht, Lehrveranstaltungen zu halten.

(4) Die entpflichteten und die in den Ruhestand versetzten Professorinnen und Professoren können im angemessenen Rahmen die Einrichtungen der Universität benutzen.

(5) Die Angehörigen der Universität sind wie die Mitglieder verpflichtet, die Freiheit von Forschung, Lehre und Studium zu wahren und die Universität bei der Erfüllung ihrer Aufgaben zu fördern. Die Angehörigen der Universität dürfen die wissenschaftlichen Einrichtungen und Betriebseinheiten nach Maßgabe der hierfür erlassenen Ordnungen benutzen.

(6) Soweit das Hochschulgesetz oder diese Grundordnung nichts anderes bestimmen, beträgt die Amtszeit der studentischen Wahlmitglieder in den Gremien ein Jahr, die Amtszeit der übrigen Wahlmitglieder vier Jahre.

=== § 3 Zentrale Organe
Zentrale Organe der Hochschule sind:

1. der Senat,
2. der Hochschulrat,
3. die Hochschulwahlversammlung,
4. die Rektorin oder der Rektor,
5. das Rektorat.

=== § 4 Senat
(1) Dem Senat gehören als stimmberechtigte Mitglieder fünfzehn Vertreterinnen oder Vertreter der Gruppe der Hochschullehrerinnen und Hochschullehrer, fünf Vertreterinnen oder Vertreter der Gruppe der akademischen Mitarbeiterinnen und Mitarbeiter, fünf Vertreterinnen oder Vertreter der Gruppe der Studierenden sowie vier Vertreterinnen oder Vertreter der Gruppe der Mitarbeiterinnen und Mitarbeiter in Technik und Verwaltung an. Nichtstimmberechtigte Mitglieder des Senats sind die Rektorin oder der Rektor, die übrigen Rektoratsmitglieder, die Dekaninnen und Dekane, die Gleichstellungsbeauftragte, die Vertrauensperson der schwerbehinderten Menschen, die oder der Beauftragte für Studierende mit Behinderung oder chronischer Erkrankung, die oder der Vorsitzende des Personalrats und des Personalrats nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=4223&anw_nr=2&aufgehoben=N&det_id=627265[§ 105 Landespersonalvertretungsgesetz] sowie der Vorsitz des Allgemeinen Studierendenausschusses oder dessen Stellvertreterinnen oder Stellvertreter.

(2) Der Senat wählt die Vorsitzende oder den Vorsitzenden und die Stellvertretung aus der Mitte seiner stimmberechtigten und nichtstimmberechtigten Mitglieder. Die oder der Vorsitzende und die Stellvertretung, die unterschiedlichen Gruppen angehören, sowie jeweils eine oder ein vom Senat gewählte Vertreterin bzw. gewählter Vertreter aus den beiden verbleibenden Gruppen bilden das Präsidium des Senats. Der Senat wird durch die Vorsitzende oder den Vorsitzenden einberufen.

=== § 5 Hochschulrat
Der Hochschulrat besteht aus der vorsitzenden Person und weiteren sieben Mitgliedern, von denen mindestens vier Externe und mindestens zwei Interne sind; mindestens drei seiner Mitglieder müssen Frauen und drei seiner Mitglieder Männer sein. Er wählt die ihm vorsitzende Person aus dem Personenkreis seiner externen Mitglieder sowie ihre Stellvertretung.

=== § 6 Hochschulwahlversammlung
(1) Die Hochschulwahlversammlung besteht in ihrer einen Hälfte aus sämtlichen Mitgliedern des Senats und in ihrer anderen Hälfte aus sämtlichen Mitgliedern des Hochschulrats. Die Mitglieder der Hochschulwahlversammlung, die zugleich Mitglieder des Senats sind, haben Stimmrecht, wenn sie auch im Senat stimmberechtigt sind. Die Mitglieder der Hochschulwahlversammlung, die zugleich Mitglieder des Hochschulrats sind, haben Stimmrecht, wenn sie Externe im Sinne des https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643712[§ 21 Abs. 3 Satz 2 HG] sind.

(2) Die oder der Vorsitzende und die Stellvertretung werden mit der Mehrheit der stimmberechtigten Mitglieder des Hochschulrats und der Mehrheit der stimmberechtigten Mitglieder des Senats gewählt (Prinzip der „doppelten Mehrheit“).

=== § 7 Rektorat
(1) Das Rektorat besteht aus der Rektorin oder dem Rektor als der oder dem Vorsitzenden, der Kanzlerin oder dem Kanzler und den Prorektorinnen oder Prorektoren. Die Rektorin oder der Rektor kann unbeschadet des https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643710[§ 19 HG] Richtlinien für die Erledigung der Aufgaben des Rektorats festlegen. Das Rektorat kann auf Vorschlag der Rektorin oder des Rektors eine ständige Vertretung und feste Geschäftsbereiche für seine Mitglieder bestimmen, in denen sie unbeschadet des https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643710[§ 19 HG] die Geschäfte der laufenden Verwaltung in eigener Zuständigkeit erledigen.

(2) Eine nichthauptberufliche Prorektorin oder ein nichthauptberuflicher Prorektor kann aus dem Kreis der Juniorprofessorinnen und Juniorprofessoren, aus der Gruppe der akademischen Mitarbeiterinnen und Mitarbeiter oder der Gruppe der Studierenden gewählt werden. Dem Rektorat können hauptberufliche Prorektorinnen oder Prorektoren angehören; darüber entscheidet auf Vorschlag des Rektorats der Senat mit der Mehrheit seiner Stimmen.

(3) Die erste Amtszeit der Mitglieder des Rektorats beträgt sechs Jahre, weitere Amtszeiten betragen vier Jahre, im Falle der Kanzlerin oder des Kanzlers sechs Jahre. Davon abweichend beträgt die Amtszeit einer Prorektorin oder eines Prorektors aus der Gruppe der Studierenden ein Jahr. Die Amtszeit der nichthauptberuflichen Prorektorinnen und Prorektoren endet spätestens mit der Amtszeit der Rektorin oder des Rektors.

(4) Die Prüfung des Jahresabschlusses erfolgt aufgrund der Hochschulwirtschaftsführungsverordnung.

(5) Die Rektorin oder der Rektor kann die Ausübung des Hausrechts im Einzelfall oder allgemein auf Mitglieder oder Angehörige der Universität übertragen.

=== § 8 Wahl der Mitglieder des Rektorats
(1) Zur Vorbereitung der Wahl von Mitgliedern des Rektorats richten Hochschulrat und Senat eine Findungskommission ein, die aus je drei Mitgliedern des Hochschulrats und des Senats besteht.

(2) Die Findungskommission tritt auf gemeinsame Einladung der Vorsitzenden des Hochschulrats und des Senats zur konstituierenden Sitzung zusammen und wählt mit einfacher Mehrheit eine Vorsitzende oder einen Vorsitzenden und eine Stellvertreterin oder einen Stellvertreter. Sie kann mit einfacher Stimmenmehrheit zur Beratung weitere Personen hinzuziehen, insbesondere Mitglieder des Hochschulrats und des Senats. Für die Arbeit der Findungskommission gelten die Regelungen der Geschäftsordnung der Hochschulwahlversammlung entsprechend, soweit dem kein höherrangiges Recht entgegensteht oder die Findungskommission im Rahmen eigener Befugnisse nicht im Einzelfall mit der Mehrheit der Stimmen ihrer Mitglieder ausdrücklich eine abweichende Organisationsentscheidung trifft.

(3) Die Positionen der hauptberuflichen Mitglieder des Rektorats werden öffentlich ausgeschrieben. Der Ausschreibungstext wird von der Findungskommission beschlossen.

(4) Nach Sichtung und Bewertung der Bewerbungen für die Position der Rektorin oder des Rektors und der Kanzlerin oder des Kanzlers beschließt die Findungskommission eine Empfehlung an die Hochschulwahlversammlung. Die Empfehlung für die Wahl der Kanzlerin oder des Kanzlers bedarf des Benehmens mit der Rektorin oder dem Rektor oder der designierten Rektorin oder dem designierten Rektor. Auf der Grundlage der Bewerbungen für die Position einer hauptberuflichen Prorektorin oder eines hauptberuflichen Prorektors unterbreitet die Rektorin oder der Rektor oder die designierte Rektorin oder der designierte Rektor einen Wahlvorschlag, zu dem die Findungskommission Stellung nimmt.

(5) Der Hochschulrat bestimmt im Benehmen mit der Rektorin oder dem Rektor oder der designierten Rektorin oder dem designierten Rektor die Zahl der nichthauptberuflichen Prorektorinnen oder Prorektoren. Die Rektorin oder der Rektor oder die designierte Rektorin oder der designierte Rektor schlägt der Hochschulwahlversammlung die Kandidatinnen oder Kandidaten für diese Ämter vor. Zu diesem Vorschlag nimmt die Findungskommission Stellung.

(6) Die Hochschulwahlversammlung lädt die vorgeschlagenen Kandidatinnen und Kandidaten (Absätze 4 und 5) zur persönlichen Vorstellung ein.

(7) Die Hochschulwahlversammlung wählt die Rektorin oder den Rektor und die Kanzlerin oder den Kanzler mit der Mehrheit der stimmberechtigten Mitglieder des Hochschulrats und der Mehrheit der stimmberechtigten Mitglieder des Senats. Ist jeweils nur eine Bewerberin oder ein Bewerber zur Wahl vorgeschlagen, so ist auf dem Stimmzettel mit ja oder nein zu stimmen. Sind mehrere Bewerberinnen oder Bewerber vorgeschlagen, so hat jedes Mitglied der Hochschulwahlversammlung eine Stimme, die durch Ankreuzen neben dem Namen der jeweiligen Bewerberin oder des jeweiligen Bewerbers oder durch Niederschreiben des entsprechenden Namens abgegeben wird. Kommen die erforderlichen Mehrheiten auch im dritten Wahlgang nicht zustande, so kann die Hochschulwahlversammlung die Findungskommission um einen neuen Wahlvorschlag nach Absatz 4 bitten oder das Wahlverfahren mit der Ausschreibung nach Absatz 3 erneut beginnen.

(8) Für die Wahl einer hauptberuflichen Prorektorin oder eines hauptberuflichen Prorektors gilt Absatz 7 entsprechend mit der Maßgabe, dass, sollte die Hochschulwahlversammlung einen neuen Wahlvorschlag erbitten wollen, diese Bitte an die Rektorin oder den Rektor oder die designierte Rektorin oder den designierten Rektor zu richten wäre und die Findungskommission zu dem neuen Wahlvorschlag wiederum Stellung nehmen könnte.

(9) Die oder der Vorsitzende der Hochschulwahlversammlung kann vorschlagen, dass über die Wahl der nichthauptberuflichen Prorektorinnen und Prorektoren in cumulo abgestimmt wird. Erreicht der Gesamtvorschlag auch im zweiten Wahlgang nicht die nach Absatz 7 erforderlichen Mehrheiten, wird über jeden Vorschlag einzeln abgestimmt. Kommen in einer Einzelabstimmung auch im zweiten Wahlgang die erforderlichen Mehrheiten nicht zustande, wird ein neuer Vorschlag erbeten; Absatz 8 gilt entsprechend.

(10) Das Wahlergebnis ist von der oder dem Vorsitzenden der Hochschulwahlversammlung unverzüglich hochschulöffentlich bekanntzugeben.

(11) Auf schriftlichen Antrag einer Mehrheit von Mitgliedern des Hochschulrats oder einer Mehrheit von Mitgliedern des Senats hat die Hochschulwahlversammlung über die Abwahl von Rektoratsmitgliedern zu entscheiden. Eine Abwahl kann nur aus wichtigem Grund erfolgen; für ihre Durchführung ist Voraussetzung, dass sie in der Einladung als Tagesordnungspunkt benannt und eine Ladungsfrist von 14 Tagen eingehalten wurde.

(12) Dem betroffenen Mitglied des Rektorats ist Gelegenheit zur Stellungnahme innerhalb einer Frist von zehn Tagen zu geben. Ist über die Abwahl der Kanzlerin oder des Kanzlers oder einer Prorektorin oder eines Prorektors zu entscheiden, ist die Möglichkeit zur Stellungnahme innerhalb der gleichen Frist auch der Rektorin oder dem Rektor einzuräumen. Unverzüglich nach der Abwahl ist das Wahlverfahren einzuleiten.

(13) Die Abwahl von Rektoratsmitgliedern erfolgt mit der einfachen Mehrheit von fünf Achteln der Stimmen der Hochschulwahlversammlung. Dabei stehen die Stimmen der Mitglieder des Hochschulrats und der Mitglieder des Senats im gleichen Verhältnis zueinander. Zur Herstellung des gleichen Stimmenverhältnisses werden die jeweiligen Stimmen der Mitglieder des Hochschulrats mit der Anzahl der ihr angehörenden stimmberechtigten Mitglieder des Senats und die jeweiligen Stimmen der Mitglieder des Senats mit der Anzahl der ihr angehörenden stimmberechtigten Mitglieder des Hochschulrats gewichtet.

=== § 9 Ausschüsse und Kommissionen
Ausschüsse und Kommissionen können im Rahmen des https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643702[§ 12 Abs. 1 HG] gebildet werden. Die Zusammensetzung der Ausschüsse und Kommissionen wird, soweit die Grundordnung nichts anderes vorsieht, von dem Organ bestimmt, das den Ausschuss oder die Kommission bildet. Dabei muss https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643699[§ 11 Abs. 2 HG] berücksichtigt werden. In Kommissionen sollen grundsätzlich alle Mitgliedergruppen vertreten sein, soweit sie von den jeweiligen Beratungsgegenständen betroffen sein können; die Mitgliedergruppen haben ein Vorschlagsrecht durch die jeweiligen Gruppenvertreter im Senat bei zentralen Gremien und im jeweiligen Fakultätsrat bei dezentralen Gremien.

=== § 10 Studienkommission
(1) Zur Umsetzung der qualifizierten Mitbestimmung nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643700[§ 11a Abs. 2 HG] wird eine Studienkommission eingerichtet. Sie hat die Aufgabe, den Senat und das Rektorat in Angelegenheiten der Lehre und des Studiums zu beraten, insbesondere in Angelegenheiten der Studienreform und der Evaluation von Studium und Lehre. Darüber hinaus hat die Kommission die Aufgabe der Qualitätsverbesserung in Lehre und Studium nach dem https://recht.nrw.de/lmi/owa/br_text_anzeigen?v_id=10000000000000000250[Studiumsqualitätsgesetz (SQG)] vom 1. März 2011. Die Kommission kann in Selbstbefassung tätig werden.

(2) Der Kommission gehören vier Vertreterinnen oder Vertreter aus der Gruppe der Hochschullehrerinnen und Hochschullehrer, vier Vertreterinnen oder Vertreter aus der Gruppe der akademischen Mitarbeiterinnen und Mitarbeiter sowie neun Vertreterinnen oder Vertreter aus der Gruppe der Studierenden an. Die Studiendekaninnen und Studiendekane der Fakultäten, die oder der AStA-Vorsitzende sowie zwei Vertreterinnen oder Vertreter aus der Gruppe der Mitarbeiterinnen und Mitarbeiter in Technik und Verwaltung gehören der Kommission in beratender Funktion an. Die Mitglieder der Kommission werden vom Senat auf Vorschlag der Gruppenvertreterinnen und -vertreter gewählt. Aus jeder Gruppe wird die entsprechende Anzahl an Stellvertreterinnen und -vertretern ohne persönliche Zuordnung zu einem Mitglied gewählt.

(3) Den Vorsitz der Kommission führt (ohne Stimmrecht) der Prorektor bzw. die Prorektorin für Lehre und Studienqualität, die Vertretung nimmt ein von der Kommission gewähltes Mitglied wahr.

(4) Die Amtszeit der oder des Vorsitzenden endet mit Ausscheiden aus dem Rektorat. Die Amtszeit der studentischen Mitglieder der Kommission beträgt ein Jahr, die der übrigen Mitglieder zwei Jahre.

=== § 11 Gleichstellungskommission
Zur Beratung und Unterstützung bei der Erfüllung des Gleichstellungsauftrags bildet der Senat eine Gleichstellungskommission. Der Gleichstellungskommission gehören je eine Frau und ein Mann aus jeder Gruppe nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643699[§ 11 Abs. 1 HG] an. Die zentrale Gleichstellungsbeauftragte der Universität ist kraft Amtes stimmberechtigtes Mitglied. Die oder der Vorsitzende wird von den stimmberechtigten Mitgliedern mit einfacher Mehrheit gewählt. Die Stellvertreterinnen der zentralen Gleichstellungsbeauftragten, die Fakultätsgleichstellungsbeauftragten und ihre Stellvertreterinnen gehören der Gleichstellungskommission mit beratender Stimme an. Die Gleichstellungskommission berichtet dem Senat.

=== § 12 Gleichstellungsbeauftragte
(1) Zur Wahrnehmung der Aufgaben nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643717[§ 24 HG] und dem Landesgleichstellungsgesetz wird eine zentrale Gleichstellungsbeauftragte bestellt.

(2) Die zentrale Gleichstellungsbeauftragte hat jeweils bis zu zwei Stellvertreterinnen aus der Gruppe der Mitarbeiterinnen in Technik und Verwaltung sowie der Studentinnen. Darüber hinaus hat sie aus jeder Fakultät bis zu zwei ständige Vertreterinnen aus der Gruppe der Hochschullehrerinnen oder der akademischen Mitarbeiterinnen.

(3) Die Bestellung der zentralen Gleichstellungsbeauftragten und ihrer Stellvertreterinnen, die Mitglieder der Universität sein müssen, erfolgt durch den Senat auf Vorschlag der Wahlfrauenversammlung. Sofern eine Fakultät die Gleichstellungsbeauftragte ihres Bereichs (Fakultätsgleichstellungsbeauftragte) und die Stellvertretung nicht aus dem Kreis der Stellvertreterinnen der zentralen Gleichstellungsbeauftragten bestellt, bedarf die Bestellung eines Vorschlags der Wahlfrauenversammlung.

(4) Die Wahlfrauenversammlung wird von den weiblichen Mitgliedern der Universität nach Gruppen getrennt gewählt. Ihr gehören je zwei Frauen aus den Gruppen nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643699[§ 11 Abs. 1 HG] an. Das Nähere regelt die Wahlordnung.

(5) Einzige Aufgabe der Wahlfrauenversammlung ist es, dem Senat für die Bestellung der zentralen Gleichstellungsbeauftragten und ihrer Stellvertreterinnen sowie der jeweiligen Fakultät für die Bestellung der Fakultätsgleichstellungsbeauftragten und ihrer Stellvertreterinnen jeweils eine oder mehrere Bewerberinnen vorzuschlagen.

(6) Für die Amtszeit der zentralen Gleichstellungsbeauftragten und ihrer Stellvertreterinnen gilt <<_2_mitglieder_und_angehörige,§ 2 Abs. 6>> entsprechend. Die Amtszeit der Stellvertreterinnen endet jedoch spätestens mit der Amtszeit der zentralen Gleichstellungsbeauftragten. Wiederbestellung ist zulässig.

(7) Die nähere Ausgestaltung des Amtes der Gleichstellungsbeauftragten sowie die Aufgaben, Rechte und Pflichten im Einzelnen sollen, soweit sie nicht gesetzlich geregelt sind, durch eine vom Senat zu beschließende Ordnung geregelt werden.

=== § 13 Vertretung der Belange studentischer Hilfskräfte
(1) Die Vertretung der Belange studentischer Hilfskräfte obliegt dem Rat für studentische Hilfskräfte (SHK-Rat). Dem SHK-Rat gehören fünf Studierende an. Er wählt aus seiner Mitte eine Vorsitzende oder einen Vorsitzenden.

(2) Wahlberechtigt zum SHK-Rat ist, wer die Berechtigung hat, die Mitglieder des Senats aus der Gruppe der Studierenden zu wählen. Wählbar ist jede oder jeder Studierende. Die Amtszeit der Mitglieder des SHK-Rates beträgt ein Jahr. In jeder Fakultät wählen die Studierenden eine Vertreterin oder einen Vertreter auf Grundlage der eingegangenen Vorschläge aus der Studierendenschaft. Gewählt ist, wer die meisten Stimmen in seiner Fakultät auf sich vereinigen kann. Scheidet ein Mitglied aus dem SHK-Rat aus, so rückt die Person mit den nächstmeisten Stimmen in der jeweiligen Fakultät nach. Im Übrigen gelten die Vorschriften für die Wahlen zum Senat aus der Gruppe der Studierenden entsprechend.

(3) Die Vorsitzende oder der Vorsitzende des SHK-Rates soll in einem angemessenen Umfang aus Mitteln der Universität für die Tätigkeit kompensiert werden.

=== § 14 Vertretung der Belange von Studierenden mit Behinderung oder chronischer Erkrankung

(1) Die Universität bestellt eine Beauftragte oder einen Beauftragten für die Belange und Bedürfnisse der Studierenden mit Behinderung oder chronischer Erkrankung. Die bestellte Person wird, sofern sie in einem Dienst oder Beschäftigungsverhältnis zur Hochschule steht, in einem angemessenen Umfang von ihrer dienstlichen Tätigkeit freigestellt. Ihr werden für die Ausübung des Amtes eine angemessene personelle und technische Unterstützung, Räumlichkeiten sowie ein Sachmittelbudget zur Verfügung gestellt.

(2) Die oder der Beauftragte wird von der Rektorin oder dem Rektor ernannt. Die Ernennung wird vom Senat bestätigt. Im Falle einer Ablehnung erfolgt ein neuer Vorschlag durch die Rektorin oder den Rektor. Die Amtszeit der oder des Beauftragten beträgt fünf Jahre.

=== § 15 Fakultäten
(1) Die Universität gliedert sich nach Maßgabe des Hochschulentwicklungsplans derzeit in folgende Fachbereiche (Fakultäten):

1. die Juristische Fakultät,
2. die Medizinische Fakultät,
3. die Philosophische Fakultät,
4. die Mathematisch-Naturwissenschaftliche Fakultät,
5. die Wirtschaftswissenschaftliche Fakultät.

(2) Organe der Fakultät sind, mit Ausnahme der Medizinischen Fakultät, der Fakultätsrat und die Dekanin oder der Dekan, die oder der durch eine Prodekanin oder einen Prodekan vertreten wird. Die Fakultäten können eine Studiendekanin oder einen Studiendekan bestellen, die oder der mit der Wahrnehmung von Aufgaben insbesondere im Bereich der Studienorganisation und der Studienplanung beauftragt wird. Die Studiendekanin oder der Studiendekan kann auch der Gruppe der akademischen Mitarbeiterinnen oder Mitarbeiter angehören. Organe der Medizinischen Fakultät sind der Fakultätsrat und das Dekanat. Die Zusammensetzung des Dekanats der Medizinischen Fakultät regelt ihre Fakultätsordnung. Die nichtmedizinischen Fakultäten können in ihrer Fakultätsordnung vorsehen, dass die Aufgaben und Befugnisse der Dekanin oder des Dekans von einem Dekanat wahrgenommen werden.

(3) Den Fakultätsräten gehören als stimmberechtigte Mitglieder acht Mitglieder aus der Gruppe der Hochschullehrerinnen und Hochschullehrer, drei Mitglieder aus der Gruppe der Studierenden und, mit Ausnahme der Medizinischen Fakultät, jeweils zwei Mitglieder aus der Gruppe der akademischen Mitarbeiterinnen und Mitarbeiter und zwei Mitglieder aus der Gruppe der Mitarbeiterinnen und Mitarbeiter in Technik und Verwaltung an. Dem Fakultätsrat der Medizinischen Fakultät gehören drei Mitglieder aus der Gruppe der akademischen Mitarbeiterinnen und Mitarbeiter an. Nichtstimmberechtigte Mitglieder des Fakultätsrates sind die Dekanin oder der Dekan als Vorsitzende oder Vorsitzender und die Prodekanin oder der Prodekan sowie, wenn die Fakultät sie oder ihn bestellt, die Studiendekanin oder der Studiendekan, in der Medizinischen Fakultät und im Fall des Abs. 2 Satz 5 das Dekanat. Die Sitze der Mitglieder aus der Gruppe der Hochschullehrerinnen und Hochschullehrer im Fakultätsrat sollen unter Berücksichtigung der fachlichen Gliederung der Fakultät vergeben werden. Gewählte Stellvertreterinnen und Stellvertreter können an den Sitzungen beratend mitwirken, sofern der Fakultätsrat keinen gegenteiligen Beschluss fasst. Mitglieder einer Fakultätskommission, der vom Fakultätsrat die Vorbereitung einer bestimmten Entscheidung übertragen worden ist, können zum Bericht der Kommission an den Sitzungen des Fakultätsrates beratend teilnehmen, sofern der Fakultätsrat keinen gegenteiligen Beschluss fasst.

(4) Die Amtszeit der Mitglieder eines Fakultätsrats beträgt zwei Jahre, die der studentischen Vertreterinnen und Vertreter ein Jahr.

(5) Die geschäftsführenden Leiterinnen und Leiter der wissenschaftlichen Einrichtungen der Fakultät bzw. die Leiterinnen und Leiter von Abteilungen des Universitätsklinikums sind zur Teilnahme an den Sitzungen des Fakultätsrates mit beratender Stimme berechtigt. Sie sollen daran teilnehmen, wenn die Belange der wissenschaftlichen Einrichtung oder Abteilung betroffen sind.

=== § 16 Wissenschaftliche Einrichtungen
(1) Die Leitung einer wissenschaftlichen Einrichtung obliegt dem Vorstand.

(2) Stimmberechtigte Mitglieder des Vorstands einer wissenschaftlichen Einrichtung (Institut, Seminar) nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643722[§ 29 HG] sind die an der wissenschaftlichen Einrichtung tätigen Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer, im Falle des Absatzes 3 nur deren gewählte Vertreterinnen und Vertreter, sowie die Vertreterinnen und Vertreter der anderen Gruppen nach Absatz 4.

(3) Der Fakultätsrat kann mit der Mehrheit der Stimmen seiner Mitglieder den Beschluss fassen, die Anzahl der Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer im Vorstand zu begrenzen. Die Vertreterinnen und Vertreter dieser Gruppe werden gewählt.

(4) Mitglieder aus den anderen Gruppen werden gewählt. Gehören dem Vorstand der wissenschaftlichen Einrichtung bis zu sieben Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer an, wird jeweils ein Mitglied, gehören ihm acht bis vierzehn Mitglieder an, werden jeweils zwei Mitglieder, anderenfalls jeweils drei Mitglieder dieser Gruppen gewählt; maßgebend ist die Zahl der Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer zum Zeitpunkt der Wahl. Gehören dem Vorstand zwei oder drei Mitglieder der Gruppe der Hochschullehrerinnen und Hochschullehrer an, so werden die Stimmen der Mitglieder dieser Gruppe doppelt gewichtet; gehört dem Vorstand ein Mitglied aus der Gruppe der Hochschullehrerinnen und Hochschullehrer an, wird dessen Stimme vierfach gewichtet.

(5) Der Vorstand wählt aus seiner Mitte eine Professorin oder einen Professor für eine Amtszeit von zwei Jahren zur geschäftsführenden Leiterin oder zum geschäftsführenden Leiter; sie oder er vertritt die wissenschaftliche Einrichtung innerhalb der Fakultät und führt deren Geschäfte in eigener Zuständigkeit. Sie oder er ist den Mitgliedern des Vorstandes gegenüber auskunfts- und rechenschaftspflichtig.

=== § 17 Universitätsklinikum
(1) Das Universitätsklinikum Düsseldorf dient der Medizinischen Fakultät der Universität zur Wahrnehmung ihrer Aufgaben in Forschung und Lehre. Die Universität und das Universitätsklinikum Düsseldorf erfüllen ihre Aufgaben in enger Zusammenarbeit.

(2) Das Nähere über die Kooperation der Universität mit dem Universitätsklinikum wird nach § 13 der Verordnung über die Errichtung des Klinikums Düsseldorf der Universität Düsseldorf (Universitätsklinikum Düsseldorf) als Anstalt des öffentlichen Rechts vom 1. Dezember 2000 in einer Kooperationsvereinbarung geregelt.

(3) Unabhängig von der Regelung des § 1 Abs. 2 der o.g. Verordnung gelten die Abteilungen und Einrichtungen des Universitätsklinikums Düsseldorf, soweit Forschung und Lehre betroffen sind, nach Maßgabe des Hochschulentwicklungsplans zugleich als wissenschaftliche Abteilungen und Einrichtungen der Medizinischen Fakultät.

=== § 18 Ehrensenatorinnen und Ehrensenatoren
Der Senat beschließt mit der Zustimmung von zwei Dritteln seiner Mitglieder über die Verleihung der Würde einer Ehrensenatorin oder eines Ehrensenators. Ein entsprechender Vorschlag erfolgt durch eine Fakultät im Einvernehmen mit dem Rektorat und im Benehmen mit den anderen Fakultäten oder durch das Rektorat im Benehmen mit den Fakultäten.

=== § 19 Allgemeine Verfahrensregeln
(1) Die Zusammensetzung von Hochschulgremien sowie Art und Umfang der Mitwirkung der Mitglieder und Angehörigen der Universität bestimmen sich nach den Aufgaben der Gremien sowie nach der fachlichen Gliederung der Universität und der Qualifikation, Funktion, Verantwortung und Betroffenheit der Mitglieder und Angehörigen der Universität. Für die Gremien Senat, Fakultätsräte, Ausschüsse, Kommissionen, Vorstände von wissenschaftlichen Einrichtungen der Fakultäten, von zentralen wissenschaftlichen Einrichtungen sowie von Abteilungen, die keine Aufgaben in der Krankenversorgung haben, gelten folgende Verfahrensgrundsätze, soweit die jeweilige Geschäftsordnung oder die Fakultätsordnung nichts anderes regeln:

1. Solange eine Vorsitzende oder ein Vorsitzender nicht gewählt ist, werden die zentralen Gremien sowie die Fakultätsräte von der Rektorin oder vom Rektor, die Gremien der Fakultäten von der Dekanin oder vom Dekan einberufen und geleitet. Den Vorsitz eines Gremiums hat ein Mitglied aus der Gruppe der Hochschullehrerinnen und Hochschullehrer inne, soweit gesetzlich nichts anderes bestimmt ist. Die oder der Vorsitzende vertritt das Gremium und führt dessen Geschäfte in eigener Zuständigkeit, bereitet die Sitzungen vor, führt die Beschlüsse aus, soweit gesetzlich nichts anderes bestimmt ist, und hat insbesondere folgende Aufgaben:

a. das Gremium einzuberufen und die Tagesordnung aufzustellen,

b. die Sitzungen zu leiten und das Hausrecht im Sitzungsraum wahrzunehmen, soweit die Befugnis von der Rektorin oder vom Rektor übertragen worden ist (https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643709[§ 18 Abs. 1 Sätze 4 u. 5 HG]),

c. auf die zügige Erfüllung der Aufgaben des Gremiums hinzuwirken.

2. Die Gremien sind beschlussfähig, wenn mehr als die Hälfte der Mitglieder anwesend ist. Nach Eröffnung der Sitzung wird die Beschlussfähigkeit überprüft, später nur nach Unterbrechung oder auf Antrag. Wahlen und Abstimmungen, die dem Antrag vorausgehen, sind gültig. Während einer Abstimmung oder Wahl ist der Antrag nicht zulässig. Über Gegenstände, die wegen Beschlussunfähigkeit vertagt wurden, kann auf der nächsten ordnungsgemäß einberufenen Sitzung beschlossen werden, auch wenn weniger als die zur Beschlussfähigkeit notwendige Zahl von Mitgliedern teilnimmt.

3. Die Gremien beraten und beschließen in ordnungsgemäß einberufenen und geleiteten Sitzungen. Die Geschäftsordnung der Gremien kann vorsehen, dass in besonderen Fällen ein Beschluss auch im Umlaufverfahren gefasst werden kann.

4. Die Teilnahme an den Sitzungen ist Pflicht der Gremienmitglieder. Im Falle zwingender Verhinderung haben sie dies vorher der oder dem Vorsitzenden unter Angabe des Grundes anzuzeigen.

5. Sofern im Hochschulgesetz, in Ordnungen und Geschäftsordnungen der Universität nichts anderes vorgeschrieben ist, bedarf ein Beschluss der einfachen Mehrheit. Stimmenthaltungen und ungültige Stimmen zählen bei der Berechnung der Mehrheit nicht.

6. Gremien können beschließen, Nichtmitglieder mit Rederecht an den Sitzungen teilnehmen zu lassen. Rederecht haben auch Personen, denen Gelegenheit zur Teilnahme an den Beratungen zu geben ist oder die als Sachkundige aus der Universität, als Sachverständige aufgrund eines förmlichen Beschlusses oder aufgrund vertraglicher Vereinbarung nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643727[§ 32 Abs. 1 HG] zugezogen worden sind. In vertraulichen Angelegenheiten sind die Nichtmitglieder zur Verschwiegenheit zu verpflichten.

7. Wahlen zu Organen sowie Entscheidungen in Personalangelegenheiten erfolgen geheim. Auf Antrag eines Mitgliedes müssen auch andere Abstimmungen geheim vorgenommen werden.

(2) Rektorat, Senat, Fakultätsräte, Dekanate und Ausschüsse geben sich eine Geschäftsordnung.

(3) Bei Entscheidungen und Beratungen der Gremien, Funktionsträgerinnen oder Funktionsträger, die nicht in einem Verwaltungsverfahren erfolgen, gelten https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=4844&anw_nr=2&aufgehoben=N&det_id=633106[§ 20 Abs. 1 Satz 1 und Satz 3 und Abs. 2 bis 5] sowie https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=4844&anw_nr=2&aufgehoben=N&det_id=633107[§ 21 Verwaltungsverfahrensgesetz] für das Land Nordrhein Westfalen entsprechend. Beteiligte oder Beteiligter im Sinne des https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=4844&anw_nr=2&aufgehoben=N&det_id=633106[§ 20 Abs. 1 Satz 1 Verwaltungsverfahrensgesetz] für das Land Nordrhein-Westfalen ist diejenige oder derjenige, die oder der durch die Entscheidung oder Beratung einen unmittelbaren Vorteil oder Nachteil erlangen kann. Amtshandlungen, die unter Mitwirkung einer nach den Sätzen 1 und 2 ausgeschlossenen Person erfolgt sind, sind von dem handelnden Gremium, der handelnden Funktionsträgerin oder dem handelnden Funktionsträger aufzuheben, wenn die Mitwirkung für das Ergebnis ausschlaggebend war oder gewesen sein könnte und Rechte Dritter nicht entgegenstehen.

=== § 20 Akademische Mitarbeiterinnen und Mitarbeiter

(1) Zur Wahrnehmung gemeinsam interessierender Angelegenheiten können sich Mitglieder der Gruppe der akademischen Mitarbeiterinnen und Mitarbeiter nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643699[§ 11 Abs. 1 Satz 1 Nr. 2 HG] nach einem in eigener Verantwortung erstellten Statut organisieren und aus ihrer Mitte ihre Sprecherinnen und Sprecher wählen. Das Statut ist dem Rektorat zur Kenntnisnahme zuzuleiten; die Wahl der Sprecherinnen und Sprecher soll der Rektorin oder dem Rektor unverzüglich angezeigt werden.

(2) Die Bestimmungen des Hochschulgesetzes über Art und Umfang der Mitwirkung der Mitglieder der Universität an den Selbstverwaltungsaufgaben bleiben unberührt.

=== § 21 Akademisches Jahr
Das Akademische Jahr beginnt mit dem Wintersemester. Zu diesem Zeitpunkt beginnt und endet in der Regel die Amtszeit aller Amtsträgerinnen und Amtsträger. Das Ende der ersten Amtszeit der nach Inkrafttreten der Grundordnung gebildeten Organe und Gremien bemisst sich so, als ob die Amtszeit zum Wintersemester nach Inkrafttreten der Grundordnung begonnen hätte.

=== § 22 Verkündungsblatt
(1) Die Universität gibt ihre Ordnungen und zu veröffentlichenden Beschlüsse in den „Amtlichen Bekanntmachungen der Heinrich-Heine-Universität Düsseldorf – Verkündungsblatt nach https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643690[§ 2 Abs. 4 Satz 2 HG]“ bekannt. Das Verkündungsblatt wird jahrgangsweise fortlaufend nummeriert und erscheint wenigstens in jedem zweiten Kalendermonat, abhängig vom Bedarf auch häufiger. Es kann elektronisch verbreitet werden.

(2) Die Rektorin oder der Rektor fertigt alle Ordnungen der Universität aus. Sie treten am Tage nach ihrer Veröffentlichung im Verkündungsblatt in Kraft, es sei denn, die Ordnung enthält eine hiervon abweichende Regelung über das Inkrafttreten.

=== § 23 Inkrafttreten
Diese Grundordnung tritt am Tage nach ihrer Veröffentlichung in den Amtlichen Bekanntmachungen der Heinrich-Heine-Universität Düsseldorf in Kraft. Gleichzeitig tritt die Grundordnung der Heinrich-Heine-Universität Düsseldorf vom 11. Juli 2007 (Amtliche Bekanntmachungen Nr. 11/2007 vom 11. Juli 2007), zuletzt geändert durch die Zweite Ordnung zur Änderung der Grundordnung vom 16. Februar 2012 (Amtliche Bekanntmachungen Nr. 4/2012 vom 17. Februar 2012), außer Kraft.