== Beitragsordnung der Studierendenschaft der Heinrich-Heine-Universität Düsseldorf
=== § 1 Erhebung von Beiträgen

(1) Von der Studierendenschaft der Heinrich-Heine-Universität Düsseldorf (im Folgenden Studierendenschaft genannt) werden in jedem Semester gemäß https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=643758[§ 57 Absatz 1 des Gesetzes über die Hochschulen des Landes Nordrhein-Westfalen] sowie gemäß xref:satzung::index.adoc#_3_rechte_und_pflichten_der_studierenden[§ 3 Absatz 3 der Satzung der Studierendenschaft] von allen immatrikulierten Studierenden der Heinrich-Heine-Universität Düsseldorf Beiträge erhoben.

(2) Die Beitragspflicht gilt auch für vom Studium beurlaubte Studierende.

(3) Die erhobenen Beiträge dienen der Erfüllung der Aufgaben der Studierendenschaft.

=== § 2 Fälligkeit der Beiträge

(1) Die Beiträge werden mit Einschreibung, Rückmeldung oder Beurlaubung fällig.

(2) Der Beitrag wird von der Heinrich-Heine-Universität Düsseldorf eingezogen.

=== § 3 Höhe der Beiträge

(1) Bei der Festsetzung der Beiträge sind die sozialen Verhältnisse der Studierenden angemessen zu berücksichtigen.

(2) Es werden folgende Beiträge je Studierender und je Semester gemäß der Tabelle im Anhang erhoben:

1. Ein Beitrag für das Semesterticket VRR/Deutschlandsemesterticket gemäß Spalte A.
2. Ein Beitrag für das Semesterticket NRW gemäß Spalte B.
3. Der AStA-Beitrag gemäß Spalte C.
4. Der Fachschaftenbeitrag gemäß Spalte D.
5. Ein Beitrag für den gemeinsamen Hochschulsport der Düsseldorfer ASten gemäß Spalte E.
6. Ein Beitrag für das Hochschulradio gemäß Spalte F.
7. Ein Beitrag für die Rückerstattung der Kosten der Semestertickets VRR und NRW bei sozialer Bedürftigkeit gemäß § 4 gemäß Spalte G.
8. Ein Beitrag für die Kooperation mit Nextbike gemäß Spalte H.
9. Ein Beitrag für die Mitgliedschaft im FZS gemäß Spalte I.

(3) Die erhobenen Beiträge müssen im Haushaltsplan der Studierendenschaft separat ausgewiesen werden.

=== § 4 Rückerstattung der Beiträge für das Semesterticket VRR/Deutschlandsemesterticket und Semesterticket NRW

(1) Bei sozialer Bedürftigkeit können die Beiträge für das Semesterticket VRR/Deutschlandsemsterticket und das Semesterticket NRW zurückerstattet werden.

(2) Die Rückerstattung erfolgt auf Antrag, bei dem die soziale Bedürftigkeit durch die/den Antragstellende/n nachzuweisen ist. Des Weiteren müssen Name, Matrikelnummer und Anschrift der/des Antragstellenden im Antrag enthalten sein. Die Anträge müssen bis 150 Tage nach Semesterbeginn beim AStA-Sozialreferat eingereicht werden.

(3) Zwei Mitglieder des Sozialreferats und ein stellvertretendes AStA-Vorstandsmitglied bilden gemeinsam die Semesterticketkommission (STK) zur Bearbeitung der Anträge. Die genaue Benennung der einzelnen Personen erfolgt per Vorstandsbeschluss.

(4) Die Bewilligung oder Zurückweisung der Anträge erfolgt nach Prüfung ebendieser durch die STK. Eine Entscheidung über die Anträge hat bis zum Ende des Semesters zu erfolgen, in dem der Antrag gestellt wurde. Anträge, die aus den Gründen, die der/die Studierende nicht selbst verschuldet hat, nach Ablauf der Antragsfrist gestellt werden, können nachträglich bewilligt werden, wenn der Haushaltsausschuss hierzu einen Beschluss fasst. Die Angelegenheit ist auf einer nichtöffentlichen Sitzung zu beraten.

(5) Folgende Personengruppen sind besonders zu berücksichtigen:

1. Studierende mit einem oder mehreren Kindern,
2. Ausländische Studierende ohne Arbeitserlaubnis in der Bundesrepublik Deutschland, die darüber hinaus keine finanzielle Förderung, beispielsweise in Form eines Stipendiums, erhalten,
3. Studierende mit Behinderung oder chronischer Erkrankung.

(6) Nicht verausgabte Mittel werden in das nächste Semester übertragen. Sollten in einem Semester die aus vergangenen Semestern rückgestellten Mittel und die Mittel aus <<_3_höhe_der_beiträge,§ 3 Abs. 2 Nummer 7>> zusammen nicht zur Erstattung aller bewilligten Semesterticketrückerstattungen ausreichen, so ist die Differenz aus dem AStA-Haushalt zu begleichen und für die nächste Änderung der Beitragsordnung in Form einer Anpassung des Beitrags nach <<_3_höhe_der_beiträge,§ 3 Absatz 2 Nummer 7>> zu berücksichtigen.

(7) Auf eine Rückerstattung besteht kein Rechtsanspruch.

=== § 5 Änderung
Diese Ordnung kann durch das Studierendenparlament mit einer Mehrheit von zwei Dritteln der
satzungsgemäßen Mitglieder geändert werden.

== Anhang – Übersicht über die erhobenen Beiträge
Spalten:

A. Semesterticket VRR/Deutschlandsemesterticket (ab SoSe 2024)
B. Semesterticket NRW
C. AStA-Beitrag
D. Fachschaftenbeitrag
E. Gemeinsamer Hochschulsport der Düsseldorfer Asten
F. Hochschulradio
G. Rückerstattung der Kosten des Semestertickets VRR/Deutschlandsemestertickets und des Semestertickets NRW bei sozialer Bedürftigkeit gemäß <<_4_rückerstattung_der_beiträge_für_das_semesterticket_vrrdeutschlandsemesterticket_und_semesterticket_nrw, § 4>>
H. Kooperation mit Nextbike
I. Mitgliedschaft im FZS

Alle Beträge sind in Euro (€) angegeben.

:fn-1: footnote:[Diese Spalte ist rein informativ und nicht rechtlich bindend; der Sozialbeitrag des Studierendenwerks ist hier nicht enthalten.]
:fn-2: footnote:[Entfällt durch die Umstellung auf das Deutschlandsemesterticket]

|===
||A |B |C |D |E |F |G |H |I |Gesamt{fn-1}

|SoSe 2024|176,40|--{fn-2}|11,00|1,00|3,00|1,50|0,25|1,50|0,40|195,05

|WiSe 2023/24|160,62|59,40|12,00|1,00|3,00|1,50|0,57|1,50|0,80|240,39

|SoSe 2023|160,62|59,40|6,00|1,00|3,00|1,50|0,05|1,50|--|233,07

|WiSe 2022/23|154,56|58,50|6,00|1,00|3,00|1,50|0,10|1,50|--|226,16

|SoSe 2022|104,28|29,25|6,00|1,00|3,00|1,50|0,35|1,50|--|146,88

|WiSe 2021/22|151,98|57,40|6,00|1,00|3,00|1,50|0,40|1,50|--|222,78

|SoSe 2021|150,81|57,40|6,50|1,00|3,00|1,50|0,20|1,50|--|221,91

|===