= Rahmengeschäftsordnung der Fachschaften der Heinrich-HeineUniversität Düsseldorf

== § 1 Organisation des Fachschaftsrates
=== (1) Wahl und Zusammensetzung der Sitzungskoordination
Die Sitzungskoordination besteht aus hauptverantwortlicher Sitzungskoordination und einer stellvertretenden Sitzungskoordination. Erst nach der Wahl der Sitzungskoordination können weitere Posten im Fachschaftsrat gewählt werden.

=== (2) Stellvertretung
Sind die Mitglieder der Sitzungskoordination nicht mehr im Amt oder anderweitig nicht in der Lage, ihren Pflichten nachzukommen, so liegt die Bekanntmachung der Fachschaftsratssitzung in der Verantwortung des an Lebensjahren ältesten Mitglied des Fachschaftsrates. Ist dieses verhindert, lädt das nächst jüngere Mitglied des Fachschaftsrates ein. Erscheint zu einer ordnungsgemäß bekanntgegebenen Sitzung des Fachschaftsrates kein Mitglied der Sitzungskoordination, so leitet das älteste anwesende Mitglied des Fachschaftsrates die Wahl temporären Sitzungskoordination für diese Sitzung.

=== (3) Sitzungsleitung
Die Sitzungskoordination bereitet die Sitzungen des Fachschaftsrates vor. Die Redeleitung leitet die Sitzungen.

=== (4) Geschäftsführung
Die Sitzungskoordination ist verantwortlich für die Koordination des Fachschaftsrates, die Durchführung der Fachschaftsratssitzungen und die Archivierung der Beschlüsse. Die E-MailBeauftragten sind für die Pflege der E-Mail-Accounts des Fachschaftsrates und Berichte bezüglich dieser verantwortlich. Die Kassenwarte sind für die Koordination und Durchführung von Finanzbeschlüssen verantwortlich. Ebenso obliegt ihnen die Aufstellung von Kassenberichten und Haushaltsplänen. Die FSVK-Beauftragten sind zur Teilnahme an der FSVK verpflichtet, sowie dem Fachschaftsrat über die FSVK zu berichten. Der Schlüsselbeauftragte ist für die Pflege des Schlüsselordners und der Kommunikation mit entsprechenden Stellen der Universität verantwortlich.

=== (5) Arbeitskreise
Zur Erfüllung der Aufgaben des Fachschaftsrates, zur Vorbereitung und Unterstützung seiner Arbeit und für Untersuchungszwecke können durch Mehrheitsbeschluss Arbeitskreise eingesetzt werden. Die Redeleitung gibt die erstmalig benannten Mitglieder und die späteren Änderungen dem Fachschaftsrat bekannt.

=== (6) Mitglieder der Arbeitskreise
Der Fachschaftsrat benennt satzungsgemäße Mitglieder der Studierendenschaft als Mitglieder der Arbeitskreise. Benennungen sind nur bei protokollierter Zustimmung des benannten Mitgliedes gültig.

=== (7) Vorsitz im Arbeitskreis
Jeder Arbeitskreis wählt einen Vorsitz aus seiner Mitte. Bis zur Wahl des Vorsitzes und nach dem Ausscheiden des Vorsitzes aus seinem Amt, nimmt die Sitzungskoordination die Aufgaben wahr.

=== (8) Ausscheiden aus den Posten der Fachschaft
Die Übernahme eines Postens oder Aufgabe der Fachschaft endet vorzeitig durch

a. Exmatrikulation,
b. Rücktritt, der der Sitzungskoordination schriftlich mitzuteilen ist,
c. Tod,
d. Beschluss der Vollversammlung,
e. Beschluss des Fachschaftsrates.

Das Mitglied informiert die Sitzungskoordination über Exmatrikulation und Rücktritt. Die Sitzungskoordination informiert das autonome Fachschaftenreferat durch ein aktualisiertes konstituierendes Protokoll über das Ausscheiden und Neubesetzen von Posten der Fachschaft. Die Sitzungskoordination informiert die einzelnen Fachschaftsräte über Beschlüsse über das Ausscheiden aus den Posten der Fachschaft. Die Beschlüsse der Vollversammlung und des Fachschaftsrates über das Ausscheiden aus einem Posten der Fachschaft benötigen je eine 2/3 Mehrheit der abstimmungsberechtigten anwesenden Personen.

=== (9) Ausscheiden aus dem Fachschaftsrat
Die Amtszeit eines Mitgliedes des Fachschaftsrates endet vorzeitig durch

a. Exmatrikulation,
b. Rücktritt, der der Sitzungskoordination schriftlich mitzuteilen ist,
c. Tod.

Das Mitglied informiert die Sitzungskoordination über die Exmatrikulation. Die Sitzungskoordination informiert das autonome Fachschaftenreferat über das Ausscheiden eines Mitgliedes des Fachschaftsrates, sowie über die Gründe hierzu. § 37 der Wahlordnung für die Wahlen zu den Organen und Gremien der Studierendenschaft der Heinrich-Heine-Universität Düsseldorf und deren Fachschaften gilt entsprechend.

== § 2 Einberufung
=== (1) Konstituierende Sitzung
Die Einberufung zur konstituierenden Sitzung erfolgt unverzüglich nach der Veröffentlichung des Wahlergebnisses durch die Wahlleitung. Die gültige Geschäftsordnung ist als Beschlussvorschlag der Einladung beizufügen. Bis zur Wahl einer Sitzungskoordination leitet die Wahlleitung die Sitzung. Die erste Amtshandlung des Fachschaftsrates ist die Wahl der Sitzungskoordination. Zuvor können keine anderen Wahlen durchgeführt oder Beschlüsse gefasst werden.

=== (2) Tagungsintervall
Der Fachschaftsrat tagt in der Regel wöchentlich und mindestens einmal pro Monat.

=== (3) Einberufung
Die Einberufung der Sitzungen unter Berücksichtigung von § 1 Abs. 1 dieser Geschäftsordnung erfolgt durch die Redeleitung in Form einer öffentlichen Bekanntmachung. Die Redeleitung hat auf Beschluss des Fachschaftsrates den Termin der nächsten Fachschaftsratsitzung bekannt zu geben. Dies hat drei Werktage vor der Sitzung an den üblichen Veröffentlichungsstellen, physikalisch und digital, zu erfolgen [Vgl. Satzung § 35 (3)]. Der Fachschaftsrat beschließt entweder einen regelmäßigen Termin für die Fachschaftsratssitzungen oder beschließt den Termin der jeweils nächsten Fachschaftsratsitzung jedesmal neu [Vgl. Satzung § 35 (2)]. Hierbei soll ein größtmöglicher Konsens zwischen den Mitgliedern des Fachschaftsrates gefunden werden. Die Sitzungen müssen in den regulären Veranstaltungszeiten der HHU Düsseldorf (8-20 Uhr) beginnen, und in den Räumlichkeiten der Heinrich-Heine-Universität Düsseldorf stattfinden.

=== (4) Bekanntmachung
Die Bekanntmachung beinhaltet die Angabe von Sitzungsort, Sitzungsbeginn, einen Tagesordnungsvorschlag, das vorläufige Protokoll der vorherigen Sitzung und die eingereichten Anträge in Kopie. Der Tagesordnungsvorschlag muss enthalten:–Feststellung der Ordnungsmäßigkeit der Bekanntmachung, Feststellung der Beschlussfähigkeit, Genehmigung der Tagesordnung, Genehmigung des Protokolls der vorherigen Sitzung (TOP 0 – Regularia)–Bericht des Fachschaftrates (TOP 1 – Berichte)–Verschiedenes (Letzter TOP der Sitzung)Bei einem regelmäßigen Termin reicht es aus, in der Bekanntmachung die Orte und Zeiten zu nennen, an denen der jeweilige Tagesordnungsvorschlag, das vorläufige Protokoll der vorherigen Sitzung und die eingereichten Anträge in Kopie eingesehen werden können.

=== (5) Frist der Bekanntmachung
Die Bekanntmachung ist ordnungsgemäß, wenn sie öffentlich drei Werktage vor der Sitzung erfolgte [Vgl. Satzung §35 (3)].

=== (6) Dringlichkeitssitzung
In Fällen von außerordentlicher Dringlichkeit muss eine Sitzung durch die Redeleitung einberufen werden, wenn dieses über die Hälfte der gewählten Mitglieder des Fachschaftsrates durch ihre Unterschrift gegenüber der Redeleitung fordern. Bei Angelegenheiten, welche eine ⅔ Mehrheit benötigen, müssen sich auch⅔ der Mitglieder des Fachschaftsrates, bei der Redeleitung für eine Dringlichkeitssitzung aussprechen. Des Weiteren verpflichten sie sich mit ihrer Unterschrift zur Teilnahme an der Dringlichkeitssitzung. Die Sitzung des Fachschaftsrates darf frühestens 24 Stunden und spätestens drei Werktage nach Erhalt der Forderung stattfinden. Alle Mitglieder des Fachschaftsrates müssen unverzüglich benachrichtigt werden. Im Fall einer dringlichen Einberufung dürfen auf dieser Sitzung keine Satzungsänderungen beschlossen und keine Wahlen beschlossen oder durchgeführt werden.

== § 3 Öffentlichkeit und Verhandlungsführung
=== (1) Öffentlichkeit
Die Sitzungen des Fachschaftsrates sind öffentlich.

=== (2) Ausschluss der Öffentlichkeit
Die Öffentlichkeit kann durch Beschluss des Fachschaftsrates für einzelne Tagesordnungspunkte ausgeschlossen werden, wenn besondere Gründe dies rechtfertigen. Die Öffentlichkeit ist auszuschließen, soweit schutzwürdige persönliche Belange behandelt werden. Die Anwesenden in einem nichtöffentlichen Teil der Sitzung sind zur Verschwiegenheit verpflichtet.

=== (3) Rederecht
In öffentlichen Sitzungen haben alle Mitglieder der verfassten Fachschaft Rederecht. Anderen Personen kann durch die Redeleitung, nicht jedoch gegen den Willen der Mehrheit der anwesenden Mitglieder des Fachschaftsrates, ein Rederecht eingeräumt werden.

=== (4) Eröffnung der Aussprache
Die Redeleitung hat über jeden Verhandlungsgegenstand, der auf der Tagesordnung steht, die Aussprache zu eröffnen, wenn sie nicht unzulässig oder an besondere Bedingungen geknüpft ist.

=== (5) Schluss der Aussprache
Ist die Redeliste erschöpft oder meldet sich niemand zu Wort, so erklärt die Redeleitung die Aussprache für geschlossen.

=== (6) Unterbrechung / Vertagung der Sitzung
Wenn während der Sitzung störende Unruhe entsteht, die den Fortgang der Verhandlungen in Frage stellt, kann die Sitzungskoordination die Sitzung auf bestimmte Zeit unterbrechen. Kann sich die Sitzungskoordination kein Gehör verschaffen, so verlasst sie ihren Platz; die Sitzung wird dadurch unterbrochen. Sieht die Sitzungskoordination einen ordnungsgemäßen Ablauf der Sitzung nicht mehr gewährleistet, vertagt sie die Sitzung.

=== (7) Öffentliche Bekanntmachung
Sieht diese Geschäftsordnung eine öffentliche Bekanntmachung vor, so erfolgt diese auf der Webseite des Fachschaftsrates. Sollte dies nicht möglich sein, so kann sie hilfsweise durch öffentlichen Aushang an den Aushangstellen der, Fachschaft durchgeführt werden. Eine Bekanntmachung auf der Webseite des Fachschaftsrates ist ohne schuldhaftes Zögern (unverzüglich) nachzuholen.

=== (8) Archivierung
Einladungen, Protokolle und Beschlüsse sind zu archivieren. Beschlüsse werden durch eine gewählte Vertretung des Fachschaftsrates auf der Webseite des Fachschaftsrates für die Dauer eines Jahres veröffentlicht. Beschlüsse werden in einem separaten Ordner archiviert. Alle Dokumente mit Ausnahme der nichtöffentlichen Teile der Sitzungsprotokolle sind für die Fachschaft einsehbar zu machen.

== § 4 Beschlussfähigkeit
=== (1) Pflicht zur Teilnahme
Jedes Mitglied des Fachschaftsrates muss zu den Sitzungen erscheinen. Jedes Mitglied ist verpflichtet, sich im Verhinderungsfalle spätestens bis zu Beginn der Sitzung bei der Sitzungskoordination zu entschuldigen. Mündliche Entschuldigungen durch Dritte sind grundsätzlich nicht statthaft.

=== (2) Anwesenheitsliste
Für jede Sitzung wird eine Anwesenheitsliste geführt, auf der die anwesenden Mitglieder des Fachschaftsrates aufgelistet werden. Anschließend werden alle nicht-Räte mit Redebeitrag, sowie alle weiteren Personen, die aufgenommen werden wollen, aufgenommen.

=== (3) Beschlussfähigkeit
Der Fachschaftsrat ist beschlussfähig, wenn die Sitzung ordnungsgemäß bekanntgegeben wurde und mehr als die Hälfte der Mitglieder des Fachschaftsrates anwesend ist.

=== (4) Feststellung der Beschlussfähigkeit
Zu Beginn jeder Sitzung (TOP 0 Regularia) ist die Beschlussfähigkeit des Fachschaftsratesfestzustellen.

=== (5) Folgen der Beschlussunfähigkeit
Wird Beschlussunfähigkeit festgestellt, muss innerhalb einer Woche, jedoch frühestens 24 Stunden nach dem Beginn der als beschlussunfähig festgestellten Sitzung, eine weitere Sitzung des Fachschaftsrats stattfinden. Sitzungskoordination und stellvertretende Sitzungskoordination müssen den Termin dieser Sitzung einstimmig bestimmen. Bei dieser ist dann die Beschlussfähigkeit unabhängig von der Anzahl der anwesenden Mitglieder gegeben. Darauf muss in der Bekanntmachung hingewiesen werden. In diesem Fall gilt nicht die normale Frist.

=== (6) Ersatztermin
In eine Bekanntmachung kann ein Ersatztermin aufgenommen werden für den Fall, dass der Fachschaftsrat auf der einberufenen Sitzung beschlussunfähig ist. Diese Bekanntmachung gilt dann auch für den Ersatztermin. Wird der Fachschaftsrat im Sitzungsverlauf beschlussunfähig, so gilt die auf dieser Sitzung beschlossene Tagesordnung auch für den Ersatztermin. Wird eine Sitzung an einem Ersatztermin abgehalten, müssen zuvor alle Mitglieder des Fachschaftsrates unverzüglich benachrichtigt werden, wenn sie auf der Sitzung nicht anwesend waren.

== § 5 Tagesordnung
=== (1) Beschluss der Tagesordnung
Zu Beginn jeder Sitzung ist über die in der Einladung vorgeschlagene Tagesordnung abzustimmen. Dazu können durch Mitglieder des Fachschaftsrats Anträge auf Änderung der vorgeschlagenen Tagesordnung gestellt werden. Mit Annahme der Tagesordnung ist diese verbindlich.

=== (2) Pflicht zur Ankündigung
Folgende Anträge können nur in die Tagesordnung aufgenommen werden, wenn sie bereits in der mit der Einladung vorgeschlagenen Tagesordnung enthalten und verschickt worden sind:

* Änderungen der fachschaftseigenen Ordnungen,
* Aufstellung des Haushalts oder von Nachtragen zum Haushalt,
* Auflösung des Fachschaftsrates,
* Wahl von Mitgliedern der Sitzungskoordination,
* Wahl von weiteren im Konstituierungsprotokoll festgehaltenen Posten der Fachschaft
* Finanzantrage (es sei denn, eine Mehrheit von zwei Drittel der anwesenden Mitglieder des Fachschaftsrates stimmt der Aufnahme eines Finanzantrages in die Tagesordnung zu).

=== (3) Nichtöffentlicher Sitzungsteil
Tagesordnungspunkte, die unter Ausschluss der Öffentlichkeit behandelt werden, sollen an das Ende der Sitzung gelegt werden.

=== (4) Anträge zur Geschäftsordnung
Geschäftsordnungsanträge sind vorrangig zu behandeln und sind in jedem Fall in das Protokoll aufzunehmen.

=== (5) Anfragen und Anträge von Studierenden
Anfragen und Anträge von Mitgliedern der verfassten Studierendenschaft, die nicht Mitglied des Fachschaftsrates sind, müssen am Anfang der Tagesordnung nach den Regularia behandelt werden.

=== (6) Verschiedenes
Der Punkt „Verschiedenes“ ist an das Ende der Tagesordnung zu setzen und soll im öffentlichen und in einem eventuellen nichtöffentlichen Teil enthalten sein. Unter dem Punkt „Verschiedenes“ dürfen keine Beschlüsse gefasst werden.

== § 6 Anträge und Anfragen
=== (1) Antragsfrist
Anträge sollen schriftlich bis zum vierten Tag vor der Sitzung bei der Sitzungskoordination eingereicht und begründet werden. Anträge, die bis vier Tage vor der Sitzung des Fachschaftsrates bei der Sitzungskoordination eingereicht worden sind, sind unter Berücksichtigung von § 5 Abs. 2 der GO in die Tagesordnung der nächsten Sitzung aufzunehmen.

=== (2) Antragsberechtigte
Antragsberechtigt sind

* die Arbeitskreise des Fachschaftsrates,
* jedes Mitglied der jeweiligen Fachschaft der Heinrich-Heine-Universität Düsseldorf im Sinne der Satzung.

=== (3) Anträge zur Sache
Die Antragsberechtigten können zu jedem Punkt der Tagesordnung und während seiner Behandlung Anträge stellen, um eine Entscheidung des Fachschaftsrates in der Sache herbeizuführen.

=== (4) Anfragen
Alle Mitglieder der jeweiligen Fachschaft der Heinrich-Heine-Universität Düsseldorf sind berechtigt, Anfragen an den Fachschaftsrat, und einzelne Mitglieder des Fachschaftsrates zu stellen. Anfragen, die das Abstimmungsverhalten betreffen, sind unzulässig. Anfragen sind bis vier Tage vor der Sitzung in schriftlicher Form bei der Sitzungskoordination einzureichen. Anfragen, die später eingereicht werden, werden auf die darauf folgende Sitzung verschoben. Anfragen müssen schriftlich beantwortet werden. Die Antworten müssen der Sitzungskoordination bis Sitzungsbeginn zugeleitet werden. Die Sitzungskoordination verliest die Antworten und leitet sie an das fragende Mitglied der Fachschaft weiter.

== § 7 Anträge zur Geschäftsordnung (GO-Anträge)
=== (1) Zweck
Der Antrag muss sich auf den zur Beratung stehenden Verhandlungsgegenstand oder auf die Tagesordnung beziehen.

=== (2) Antragstellung
Liegt eine Meldung für einen GO-Antrag vor, so erhält das antragstellende Mitglied des Fachschaftsrates umgehend, spätestens nach dem aktuellen Redebeitrag, das Wort. Um eine Meldung für einen GO-Antrag deutlich zu machen, hebt das Mitglied gleichzeitig beide Hände. GOAnträge müssen positiv, also ohne Verneinung gestellt werden.

=== (3) Behandlung und Beschlussfassung
Auf einen GO-Antrag kann eine Gegenrede folgen. Diese kann auch formal erfolgen. Einer inhaltlichen Gegenrede ist der formalen Gegenrede der Vorzug zu geben. Auf die Gegenrede ist keine weitere Wortmeldung zulässig. Erfolgt eine Gegenrede, wird unverzüglich über den GO- Antrag abgestimmt, falls das Antrag stellende Mitglied diesen nicht zuvor zurückzieht. Erfolgt keine Gegenrede, ist der GO-Antrag angenommen. Wird vor der Abstimmung ein weiterer GO-Antrag gestellt, muss dieser weiterführend sein, um sofort berücksichtigt zu werden. In diesem Fall wird über den weiterführenden GO-Antrag abgestimmt. Zur Geschäftsordnung dürfen Einzelne nicht langer als fünf Minuten sprechen.

=== (4) Inhalt
GO-Anträge sind:

1. Änderung der beschlossenen Tagesordnung,
2. Schluss der Aussprache und sofortige Beschlussfassung oder Beendigung des Tagesordnungspunktes,
3. Namentliche Abstimmung,
4. Geheime Abstimmung,
5. Feststellung der objektiven Unklarheit über den Inhalt oder die Nicht-Ordnungsmäßigkeit einer Beschlussfassung oder einer Wahl und sofortige Wiederholung dieser Beschlussfassung oderdieses Wahlganges,
6. Erneute Feststellung der Beschlussfähigkeit,
7. Unterbrechung der Sitzung für einen bestimmten Zeitraum (<= 15 Minuten),
8. Beschränkung der Redezeit,
9. Schluss der Redeliste,
10. Nichtbefassung eines Antrages,
11. Antrag zur vorübergehenden Aussetzung eines Tagesordnungspunktes,
12. Vertagung eines Punktes der Tagesordnung,
13. Wiedereintritt in die Aussprache,
14. Gemeinsame Aussprache über gleichartige oder im Sachzusammenhang stehende Verhandlungsgegenstände,
15. Vertagung der Sitzung,
16. Einräumung eines Rederechts für Personen, die nicht Mitglied der verfassten Fachschaft sind,
17. Zulassung von Einzelnen zur nichtöffentlichen Sitzung,
18. En-Bloc-Abstimmung mehrerer Anträge,
19. Tagesordnungspunkt im weiteren Verlauf für die Öffentlichkeit schließen,
20. Entzug des Rederechts eines nicht-Fachschaftsrates für den aktuellen Tagesordnungspunkt,
21. Sitzungsverweis einer Person ohne Rederecht.

=== (5) Sonderbestimmungen
* Anträge nach Abs. 4 Nr. 1 bis Nr. 2 bedürfen der Mehrheit von mindestens zwei Dritteln der anwesenden Mitglieder des Fachschaftsrates.

* Ein Antrag nach Abs. 4 Nr. 1 ist nicht mehr zulässig, sobald der Punkt „Verschiedenes“ aufgerufen worden ist.

* Der Beschluss eines Antrages nach Abs. 4 Nr. 2 kann durch eine Mehrheit von mindestens zwei Dritteln der anwesenden Mitglieder des Fachschaftsrates aufgehoben werden. Dieser Antrag auf Aufhebung eines solchen Beschlusses kann zu einem Tagesordnungspunkt nur einmal gestellt werden.

* Ein Antrag nach Abs. 4 Nr. 3 gilt bei Gegenrede als abgelehnt.

* Abweichend von Abs. 2 kann jedes anwesende Mitglied der verfassten der jeweiligen Fachschaft einen Antrag nach Abs. 4 Nr. 3 stellen.

* Anträge nach Abs. 4 Nr. 3 und 4 sind nicht zulässig bei Abstimmungen über GO-Anträge.

* Über einen Antrag nach Abs. 4 Nr. 4 wird nicht abgestimmt.

* Bei Anträgen nach Abs. 4 Nr. 4 bis Nr. 7 ist keine Gegenrede zulässig.

* Ein Antrag nach Abs. 4 Nr. 7 bedarf bei drittmaligen Antrag innerhalb einer Stunde Sitzungszeit einer Abstimmung.

* Über die Zulässigkeit eines Antrages nach Abs. 4 Nr. 5 entscheidet die Sitzungskoordination, gegebenenfalls nach Rücksprache mit dem autonomen Fachschaftenreferat oder weiteren Stellen des AStA. Hierzu kann ein Beschluss zurückgestellt und vertagt werden, wenn die Mehrheit der anwesenden Fachschaftsräte dies als notwendig erachtet. Erklärt die Sitzungskoordination den Antrag für nicht zulässig, kann die antragstellende Person den Rechtsausschuss anrufen. Dieser entscheidet binnen drei Wochen ab Anrufung. Der Beschluss des Fachschaftsrates ist bis zu einer verbindlichen Entscheidung des Rechtsausschusses unwirksam.

* Ein Antrag nach Abs. 4 Nr. 7 kann von jedem Mitglied des Fachschaftsrates zu jedem Tagesordnungspunkt nur einmal beantragt werden. Hierbei kann eine Dauer von 2 Minuten nicht unterschritten werden, sowie eine Dauer von 15 Minuten nicht überschritten werden.

* Vor Abstimmung über einen Antrag nach Abs. 4 Nr. 9 sind die noch auf der Redeliste befindlichen Personen zu verlesen. Vor Schluss der Redeliste ist jeder anwesenden Person mit Rederecht Gelegenheit zu geben, sich noch auf diese setzen zu lassen.

* Ein Antrag nach Nr. 18 gilt bei Gegenrede als abgelehnt.

* Ein Antrag nach Nr. 21 benötigt mindestens eine zwei Drittel Mehrheit der anwesenden Mitglieder des Fachschaftsrates.

== § 8 Abstimmung und Beschlussfassung
=== (1) Eröffnung der Beschlussfassung
Die Redeleitung eröffnet nach Abschluss der Aussprache und Wiederholung der Wortlaute der Anträge die Beschlussfassung.

=== (2) Stimmberechtigung
Stimmberechtigt sind die anwesenden Mitglieder des Fachschaftsrates.

=== (3) Änderungsantrage
Sind zu einem Antrag Änderungsanträge gestellt worden, so ist über diese vor dem Hauptantrag zu beschließen. Soweit der Fachschaftsrat den Änderungsanträgen zustimmt oder sie von der antragstellenden Person den Hauptantrag übernommen werden, wird der Hauptantrag in der geänderten Fassung zur Beschlussfassung gestellt. Die antragstellende Person des Hauptantrages hat bis zur endgültigen Beschlussfassung das Recht, auch eine geänderte Fassung ihres Antrages zurückzuziehen.

=== (4) Konkurrierende Anträge
Liegen konkurrierende Anträge vor, so hat die Redeleitung die Beschlussfassung wie folgt
durchzuführen:

1. Geht ein Antrag weiter als ein anderer, so ist über den weitergehenden Antrag zuerst zu beschließen. Wird dieser angenommen, so werden weniger weitgehende Anträge nicht mehrbehandelt.
2. Lässt sich eine Reihenfolge im Sinne von Nr. 1 nicht feststellen, so bestimmt sich die Reihenfolge, in der konkurrierende Anträge zur Beschlussfassung gestellt werden, nach der Reihenfolge der Antragstellung. Lässt sich diese nicht mehr feststellen, entscheidet die Redeleitung. In der Schlussabstimmung werden einander widersprechende Anträge gegeneinander abgestimmt.

=== (5) Namentliche Abstimmung
Auf Verlangen eines Mitgliedes der verfassten Studierendenschaft der jeweiligen Fachschaft ist namentlich abzustimmen, es sei denn ein Mitglied des Fachschaftsrates widerspricht (§7 Abs. 4 Nr. 3 GO).

=== (6) Geheime Abstimmung
Auf Verlangen eines Mitgliedes des Fachschaftsrates ist geheim abzustimmen (§7 Abs. 4 Nr. 4 GO).

=== (7) Abstimmung
Abstimmungen erfolgen durch geeignetes Anzeigen der Stimme der Stimmberechtigten. Ein geeignetes Anzeigen der Stimme bedeutet der Abstimmungsart entsprechend, für die Redeleitung eindeutig auszählbar, und für jeden Stimmberechtigten durchführbar. Die Auszählung der Stimmen erfolgt durch die Redeleitung.

=== (8) Mehrheitsfindung
Für Beschlüsse genügt die einfache Mehrheit der abgegebenen Stimmen, wenn die Satzung der verfassten Studierendenschaft oder diese Geschäftsordnung keine anderen Regelungen vorsieht. Beschlusse zur Aufstellung, Änderung oder Ergänzung der eigenen Satzung/Geschäftsordnung/Wahlordnung bedürfen einer Mehrheit zwei Dritteln der anwesenden satzungsgemäßen Mitglieder der Fachschaft auf einer Vollersammlung. Eine Anwesenheitsliste inklusive Unterschriften ist auf einer solche Vollversammlung zu führen. Diese Aufstellungen, Änderungen und Ergänzungen bedürfen eine Zustimmung des Studierendenparlaments, um wirksam zu sein. Das autonome Fachschaftenreferat ist über diese Aufstellung, Änderungen und Ergänzungen unverzüglich zu informieren.

=== (9) Aufklarung über die Mehrheitsfindung
Soweit für einen Beschluss nicht lediglich eine einfache Mehrheit erforderlich ist, hat die Redeleitung vor der Beschlussfassung darauf hinzuweisen.

=== (10) Stimmenzählung
Ungültige Stimmen und Stimmenthaltungen zählen bei der Ermittlung der Mehrheit nicht mit. Bei Gleichheit der Stimmen gilt ein Antrag als abgelehnt. Ein Beschluss ist nicht gültig, wenn sich mindestens die Hälfte der Abstimmenden der Stimme enthalten.

=== (11) Sondervotum
Jedes Mitglied des Fachschaftsrates kann seine vom Mehrheitsbeschluss abweichende Meinung in einem Sondervotum schriftlich artikulieren. Das Sondervotum muss in der Sitzung vorgetragen und begründet werden. Sondervoten müssen der Sitzungskoordination binnen 24 Stunden zugeleitet werden, um ins Protokoll aufgenommen zu werden. Soweit Beschlüsse anderen Stellen zugeleitet oder der Öffentlichkeit zuganglich gemacht werden, sind auch die zu Protokoll genommenen Sondervoten weiterzuleiten oder zu veröffentlichen.

=== (12) Einspruch
Einspruch gegen einen Beschluss ist als Antrag nach §8 Abs. 4 Nr. 5 der GO möglich. Über die Zulässigkeit dieses Antrages entscheidet die Sitzungskoordination. Die Beanstandung eines Beschlusses oder einer Wahl kann auch gegenüber dem Rechtsausschuss erklärt werden. Wenn ein Verstoß gegen die Satzung des Studierendenparlamentes oder rechtliche Regelungen vorlag, hat die Redeleitung den entsprechenden Beschluss zu beanstanden.

=== (13) Aufhebung von Beschlüssen
Beschlüsse des Fachschaftsrates können mit der Mehrheit der satzungsgemäßen Mitglieder aufgehoben werden. Eine Aufhebung ist nur dann möglich, wenn zu diesem Tagesordnungspunkt mit entsprechendem Hinweis eingeladen wurde. Beschlüsse der Vollversammlung können nur mit einer 2/3 Mehrheit der satzungsgemäßen Mitglieder der Fachschaft aufgehoben werden.

=== (14) Wahlen
Wahlen erfolgen nach der Satzung und der Wahlordnung der verfassten Studierendenschaft der Heinrich-Heine-Universität Düsseldorf.

== § 9 Schriftführung
=== (1) Protokoll
Eine protokollierende Person fertigt ein Protokoll der Sitzung an.

=== (2) Inhalt des Protokolls
Das Protokoll muss enthalten:

* Datum und Uhrzeit des Beginns und des Endes der Sitzung,
* eine Anwesenheitsliste [gemäß § 4 Abs. 3],
* die beschlossene Tagesordnung,- die Texte der Anträge,
* die Beschlüsse im Wortlaut und die Ergebnisse der Abstimmungen,
* auf Antrag die vom Mehrheitsbeschluss abweichende Meinung eines Mitgliedes des Fachschaftsrates (Sondervotum) nach § 8 Abs. 11 der GO,
* die Unterschrift der protokollierenden Person und der Redeleitung.

=== (3) Veröffentlichung des Protokolls
Das genehmigte Protokoll wird öffentlich durch Aushang und in digitaler Form bekannt gemacht. Der Fachschaftsrat archiviert die unterzeichnete Ausfertigung des Protokolls. Waren Teile der Sitzung nichtöffentlich, so sind die Protokollteile darüber nur den Mitgliedern des Fachschaftsrates und seiner Ausschüsse sowie dem AStA und seinen Beschäftigten zugänglich.

=== (4) Genehmigung des Protokolls
Das Protokoll wird zu Beginn der folgenden Sitzung durch den Fachschaftsrat genehmigt, nachdem sich seine Mitglieder von der Richtigkeit überzeugt haben.

=== (5) Beschlussausfertigung
Beschlüsse des Fachschaftsrates werden von der Sitzungskoordination ausgefertigt, unterzeichnet, und schnellstmöglich, jedoch spätestens sieben Tage nach der Sitzung öffentlich bekannt gemacht.

=== (6) Aktenführung
Geschäfts- und Schriftführung des Fachschaftsrates sind so zu gestalten, dass beim Amtswechsel sämtliche Vorgänge aus den Akten eindeutig zu rekonstruieren sind. Mitglieder des Fachschaftsrates haben das Recht, die Akten jederzeit einzusehen.

== § 10 Sonstige Bestimmungen
=== (1) Kontaktdaten
In der Konstituierenden Sitzung müssen Kontaktdaten der gewählten Ratsmitglieder festgehaltenwerden. Der Fachschaftsrat, das autonome Fachschaftenreferat, das Finanzreferat und die Buchhaltung des AStA erhalten Zugriff auf diese Daten. Die Kontaktdaten müssen laufend aktualisiert werden. Die Mitglieder des Rates sind verpflichtet, den Fachschaftsrat und das autonome Fachschaftenreferat über Veränderungen ihrer Kontaktdaten unverzüglich zu unterrichten.

=== (2) Mobiltelefone
Sämtliche Anwesende haben während der Sitzungen des Fachschaftsrates im Raum dafür Sorge zu tragen, dass ihre Mobiltelefone auf lautlos geschaltet sind. Die übermäßige Nutzung von Mobiltelefonen ist während der Sitzung zu vermeiden.

=== (3) Zeitliche Begrenzung der Sitzungen
Nach 22.30 Uhr und nach 120 Minuten nach Sitzungsbeginn darf kein Tagesordnungspunkt außer „Verschiedenes“ aufgerufen werden, es sei denn, mindestens zwei Drittel der anwesenden Mitglieder des Fachschaftsrates sprechen sich für eine Fortführung der Sitzung aus.

== § 11 Auslegung der Geschäftsordnung
Ist in einer Sitzung strittig, wie eine Bestimmung dieser Geschäftsordnung auszulegen ist, oder ist das Verfahren strittig, so entscheidet der Fachschaftsrat mit Mehrheit der anwesenden Mitglieder über den Fortgang der Verhandlung. Bei Gleichheit der Stimmen entscheidet die Redeleitung. Gegen diese Entscheidung kann der Rechtsausschuss angerufen werden.

== § 12 Schlussbestimmungen
=== (1) [Inkrafttreten]
Die Geschäftsordnung tritt mit Bekanntmachung gemäß § 5 Absatz 2 der Satzung der Studierendenschaft in Kraft. Dies gilt auch für Änderungen.

=== (2) Änderungen
Für Änderungen gilt § 40 Absatz 8 der Satzung der Studierendenschaft.

=== (3) Geltung für andere Gremien
Diese Geschäftsordnung gilt auch für die Fachschaftsvollversammlung der Fachschaft, sofern diese keine eigene Geschäftsordnung beschlossen hat und keine andere Bestimmung dem entgegensteht. Sie gilt auch für Gremien, die von der Fachschaftsvollversammlung oder vom Fachschaftsrat eingesetzt worden sind, sofern sie keine Änderungen beschließen oder sich eine eigene Geschäftsordnung gegeben haben, die dann der Zustimmung des eingesetzten Gremiums bedürfen und soweit andere Bestimmungen dem nicht entgegenstehen. Bei dem Verfahren in den Gremien und auf der Fachschaftsvollversammlung tritt an die Stelle des Fachschaftsrates das Gremium bzw. die Fachschaftsvollversammlung, an die Stelle der Mitglieder des Fachschaftsrates die Mitglieder des Gremiums bzw. die Mitglieder der Fachschaftsvollversammlung und an die Stelle der Sitzungskoordination tritt der Vorsitz des Gremiums bzw. die Versammlungsleitung.