= Reisekostenrichtlinie der Studierendenschaft der Heinrich-Heine-Universität Düsseldorf

=== § 1 Zweck
(1) Der Zweck dieser Richtlinie ist die Regelung der Erstattung von Reisekosten und weiteren Aufwendungen, die einem Mitglied des AStA oder den Mitgliedern des Studierendenparlamentes und seiner Arbeitskreise und Ausschüssen im Rahmen ihrer Ämter oder Ausübung der Tätigkeiten für die Studierendenschaft entstehen.

(2) Ebenfalls sind einem Fachschaftsratsmitglied die Reisekosten zu erstatten, wenn es glaubhaft machen kann, dass seine Reise im Rahmen der satzungsgemäßen Aufgaben für die Studierendenschaft erfolgt und keine Abrechnung über andere Stellen möglich ist.

(3) Ebenfalls sind Mitgliedern von Fachschaften die Reisekosten und die Teilnahmebeiträge, die durch die Teilnahme an einer Bundesfachschaftentagung oder einer vergleichbaren Veranstaltung entstehen, zu erstatten. Die Erstattung ist je Fachschaft auf zwei Reisen innerhalb eines Haushaltsjahres je studierbaren Grundstudiengang (Staatsexamen oder Bachelor), nur in Ausnahmefällen auch je Masterstudiengang, von höchsten vier Personen je Reise beschränkt. Die Reisegruppe einer Fachschaft, die an einer Veranstaltung teilnimmt, soll genderquotiert sein.

=== § 2 Fälligkeit der Beiträge
(1) Notwendige Fahrtkosten werden grundsätzlich erstattet. Anträge auf Fahrtkostenerstattung müssen schriftlich beim Finanzreferat eingereicht werden. Sie müssen den Grund der Erstattung und die entstandenen Kosten aufführen. Die Fahrtkostenbelege sind im Original beizufügen. Bei Anträgen, die später als zwei Monate nach Beendigung der Reise oder nach Beendigung des Haushaltsjahres, in dem die Reise stattfand, eingereicht wurden, besteht grundsätzlich kein Recht auf Erstattung. Das Finanzreferat kann in Absprache mit dem Vorstand und bei Anträgen aus den Fachschaften in Absprache mit dem Fachschaftenreferat in begründeten Fällen Ausnahmen zulassen.

(2) Bei der Reise mit regelmäßig verkehrenden Beförderungsmitteln wird grundsätzlich nur die niedrigste Klasse erstattet. Bei triftigen Gründen kann abgewichen werden, dies muss im Antrag begründet werden. Die Beförderung in einer höheren Klasse wird zugelassen, wenn sie nachweislich günstiger ist. Tickets sind unverzüglich nach Erhalt der Anmeldebestätigung zu kaufen. Beförderungsleistungen im Rahmen des Semestertickets werden grundsätzlich nicht erstattet.

=== § 2a Reisekostenerstattung bei der Nutzung von Kraftfahrzeugen und Fahrrädern
(1) Notwendige Kraftfahrzeugreisen werden mit einer Wegstreckenentschädigung von 30 Cent je Kilometer, für ein zweirädriges Kraftfahrzeug mit 13 Cent je Kilometer entschädigt.

(2) Die Kraftfahrzeugreise ist notwendig, wenn entweder

1. geeignete regelmäßig verkehrende Beförderungsmittel nicht zur Verfügung stehen,
2. regelmäßig verkehrende Beförderungsmittel gegenüber der Kraftfahrzeugreise mit Mehrkosten verbunden wäre oder
3. mit der Nutzung von regelmäßig verkehrende Beförderungsmittel erheblicher Mehraufwand für die Reisenden im Vergleich zu einer Kraftfahrzeugreise, insbesondere durch nächtliches Reisen oder das Transportieren von unhandlichen Gegenständen, verbunden wäre.

(3) Standen geeignete regelmäßig verkehrende Beförderungsmittel nicht zur Verfügung oder lagen andere triftige Gründe für die Benutzung eines Fahrrades vor, können auch die Reisekosten für die Nutzung eines Fahrrades erstattet werden. Der Erstattung erfolgt als eine Wegstreckenentschädigung von 6 Cent je Kilometer.

(4) Benutzen mehrere nach <<_1_zweck, § 1>> Erstattungsberechtigte ein Kraftfahrzeug oder ein Fahrrad für eine Reise gemeinsam, so wird die Wegstreckenentschädigung um 2 Cent je Person und Kilometer erhöht.

(5) Für die Berechnung der Wegstreckenentschädigung ist die kürzeste verkehrsübliche Straßenverbindung maßgebend. Das Anfang oder das Ende der Verbindung bestimmt 3
nach der Wohnung der Erstattungsberechtigten, je nachdem ob es sich um eine Hin- oder Rückfahrt handelt; andernfalls nach den tatsächlichen Start- und Zielorten.

(6) Standen geeignete regelmäßig verkehrende Beförderungsmittel und keine privaten Kraftfahrzeuge zur Verfügung, so können auch die tatsächlich angefallenen Kosten für die Beförderung durch Taxen erstattet werden.

=== § 3 Weitere Reisekostenerstattungen
(1) Notwendige Übernachtungskosten werden grundsätzlich erstattet. Die Originalbelege sind, wenn beides beantragt wird, gemeinsam mit denen für die Fahrtkostenerstattung einzureichen.

(2) Je vollem Kalendertag werden 24 EUR, für einen halben Tag (12 Stunden) werden 12 EUR und für Aufenthalte von acht bis elf Stunden 6 EUR als zusätzlicher Verpflegungsaufwand erstattet. Es wird nur Aufwand für die Verpflegung ersetzt, die über das Angebot der Veranstaltung oder Übernachtungsmöglichkeit hinausgeht.

(3) Kosten, die keine Reise- oder Übernachtungskosten sind, können als Nebenkosten erstattet werden.

=== § 4 Abweichende Bestimmungen bei Bundesfachschaftentagungen und ähnliche Veranstaltungen
(1) Für Erstattungen nach <<_1_zweck, § 1 Absatz 3>> gelten die allgemeinen Bestimmungen dieser Richtlinie, soweit sich aus den Absätzen 2 bis 4 nichts anderes ergibt.

(2) Sollte im Krankheitsfall eine Reise nicht angetreten werden, kann eine Erstattung nur mit Nachweis eines ärztlichen Attests erfolgen.

(3) Tickets sind unverzüglich, spätestens drei Wochen vor Fahrtantritt, zu kaufen.

(4) Anträge sind in schriftlich an das Fachschaftenreferat zu richten, das die Anträge auf Richtigkeit prüft und die Höhe der Erstattung empfiehlt. Die Anträge sind zusammen mit der Empfehlung vom Fachschaftenreferat an das Finanzreferat weiterzuleiten.

(5) Die FSVK kann ergänzende Bestimmungen bezüglich der Prüfung der Anträge durch das Fachschaftenreferat und die zu erbringenden Nachweise beschließen.

=== § 5 Ergänzende Bestimmungen
(1) Die in dieser Richtlinie beschriebenen Kosten sind im Sinne des Landesreisekostengesetzes (LRKG NRW) als Dienstreisekosten zu verstehen. In Streitfragen sind die Vorschriften des LRKG NRW entsprechend anzuwenden.

(2) Bei Anwendung der Reisekostenrichtlinie können pro Person und Reise nur Kosten bis zu dem in xref:satzung::index.adoc#_49_umbenennung_einer_fachschaft[§ 49 Absatz 2] der Satzung genannten Höchstbetrag erstattet werden. Die Erstattung von Reisekosten über diesen Betrag hinaus bedarf der Zustimmung des SP.