= Darlehensordnung für die Vergabe von Darlehen durch die Studierendenschaft der Heinrich-Heine-Universität Düsseldorf

_Die Vergabe von Darlehen ist eine freiwillige Leistung des AStA, auf die kein Rechtsanspruch besteht._

== I. Allgemeines
=== § 1 Geltungsbereich
Diese Ordnung regelt die Vergabe von Darlehen an Studierende der Heinrich-HeineUniversität Düsseldorf durch die Organe und Gremien der Studierendenschaft und der Fachschaften.

=== § 2 Zuständigkeiten
(1) Zur Entscheidung über Darlehensanträge wird der Gemeinsame Darlehensausschuss (GDA) gebildet, der jeweils aus einer Vertreterin oder einem Vertreter des Finanzreferates und einer weiteren durch Beschluss des AStA-Vorstandes zu benennenden Person besteht.

(2) Der AStA-Vorstand benennt per Vorstandsbeschluss eine oder mehrere Personen zur Schulden- und Budgetberatung des AStA.

(3) Die Schulden- und Budgetberatung des AStA berät Studierende in Bezug auf Darlehensanträge, nimmt diese entgegen, und leitet sie an den GDA weiter.

(4) Das Finanzreferat überwacht die ordnungsgemäße Abwicklung gewährter Darlehen. Für Sachverhalte nach <<_9_inhaltliche_prüfung, § 9 Absatz 3>> sowie <<_16_entscheidungsbefugnisse, § 16 Absatz 2>> dieser Ordnung ist die Zustimmung des Haushaltausschusses (HHA) notwendig.

(5) Sofern persönliche Darlehensangelegenheiten im HHA oder anderen Gremien der Studierendenschaft behandelt werden, darf dies nur unter Ausschluss der Öffentlichkeit
geschehen.

(6) Darlehen können nur über das in dieser Ordnung geregelte Verfahren vergeben werden. Eine Vergabe von Darlehen durch andere Stellen innerhalb der Studierendenschaft, insbesondere durch die Fachschaften und deren Organe, ist ausgeschlossen.

== II. Antragsverfahren
=== § 3 Antragsberechtigung
(1) Alle Mitglieder der verfassten Studierendenschaft der Heinrich-Heine-Universität Düsseldorf sind antragsberechtigt.

(2) Studierende sind von der Antragsstellung ausgeschlossen, wenn sie gemäß <<_5_mitteilungspflicht, § 5 Absatz 4>> von der Darlehensvergabe ausgeschlossen wurden.

(3) Noch nicht eingeschriebene Personen, die sich an der Heinrich-Heine-Universität einschreiben wollen, dies jedoch aufgrund von Bedürftigkeit gemäß <<_10_bedürftigkeit, § 10 Absatz 1 Nummer 1>> nicht umsetzen können, sind ebenfalls antragsberechtigt. Der Sozialbeitrag dieser Personen wird vom AStA an die Heinrich-Heine-Universität überwiesen.

(4) Es besteht kein Rechtsanspruch auf die Gewährung eines Darlehens.

=== § 4 Antragstellung
Der Antrag ist schriftlich mit dem vollständig ausgefüllten Antragsformular (gemäß Anlage 1) und allen notwendigen Anlagen bei der Schulden- und Budgetberatung des AStA einzureichen.

=== § 5 Mitteilungspflicht
(1) Die Antragstellenden verpflichten sich, der Schulden- und Budgetberatung alle für den Entscheidungsprozess notwendigen Informationen und Unterlagen vollständig zur Verfügung zu stellen.

(2) Die Antragstellenden versichern mit ihrer Unterschrift, dass alle im Antrag angeführten Sachverhalte der Wahrheit entsprechen. Bei vorsätzlichen oder grob fahrlässig falschen Angaben zur Ermittlung des Darlehens kann der Darlehensgeber das Darlehen fristlos kündigen. In diesem Fall ist die verbliebene Darlehensschuld zur sofortigen Rückzahlung fällig.

(3) Die Antragstellenden sind verpflichtet, Änderungen ihrer persönlichen finanziellen Verhältnisse sowie Änderungen der Angaben gemäß <<_6_inhalt_des_antrages, § 6 Absatz 2>> unverzüglich dem Sozialreferat des AStA zu melden.

(4) Studierende, die gegen die Regelungen der Absätze 1 bis 3 verstoßen, können durch den GDA nach pflichtgemäßem Ermessen von der Darlehensvergabe dauerhaft ausgeschlossen werden.

(5) Kommt die antragstellende Person der Mitteilungspflicht nicht nach, kann die Schuldenund Budgetberatung Auskunft bei der Meldebehörde einholen. Etwaige Kosten für die Einholung von personenbezogenen Daten werden auf die Schuldnerin oder den Schuldner umgelegt.

=== § 6 Inhalt des Antrages
(1) Der Antrag ist zu begründen. Die Begründung muss darlegen, warum die Gewährung des Darlehens erforderlich ist. Sie muss einen umfassenden Einblick in die wirtschaftlichen Verhältnisse und die Vermögensverhältnisse der jeweiligen Antragstellenden ermöglichen, insbesondere aus welchen Mitteln die Rückzahlung bestritten werden soll.

(2) Zur Person der jeweiligen Antragstellenden sind folgende Angaben erforderlich:

1. Name und Vorname
2. Geburtsdatum
3. Anschrift
4. Familienstand
5. Matrikelnummer
6. Studienfach bzw. –fächer
7. Semesterzahl
8. Telefonnummer
9. E-Mail-Adresse
10. Bankverbindung
11. Angaben zum Namen und Vornamen, Geburtsdatum, Einkommensverhältnis und Verhältnis zum Antragsstellenden der Personen, die mit im Haushalt leben.

=== § 7 Anlagen
Bei Antragstellung sind vorzulegen:

1. ein gültiges Personaldokument mit Lichtbildausweis,
2. eine gültige Immatrikulationsbescheinigung, ggf. die Rückmeldung zum folgenden Semester,
3. Belege über weitere Voraussetzungen der Antragsberechtigung gemäß <<_3_antragsberechtigung, § 3 Absatz 1>>,
4. Belege über weitere Angaben gemäß <<_6_inhalt_des_antrages, § 6 Absatz 2>>,
5. ggf. Belege über die Aufenthaltserlaubnis bei ausländischen Studierenden,
6. ggf. Kopie des Visums bei ausländischen Studierenden,
7. in den Fällen des <<_10_bedürftigkeit, § 10 Absatz 2>> eine Geburtsurkunde.
8. In den Fällen des <<_10_bedürftigkeit, § 10 Absatz 1 Nummer 5>> eine Bescheinigung über die gegenwärtige Beratung der*des Antragstellenden in einer Fachberatungsstelle.

== III. Antragsbearbeitung
=== § 8 Formelle Prüfung
(1) Die Schulden- und Budgetberatung des AStA prüft nach Erhalt eines Antrages unverzüglich, ob

1. die Antragsberechtigung gemäß <<_3_antragsberechtigung, § 3>> gegeben ist und
2. die Formvorschriften der §§ <<_4_antragstellung, 4>> bis <<_7_anlagen, 7>> erfüllt sind.

(2) Werden bei der Prüfung gemäß Absatz 1 keine Mängel festgestellt, ist der Antrag zur inhaltlichen Prüfung und Entscheidung unverzüglich an den GDA zu übergeben.

(3) Wird bei der Prüfung gemäß Absatz 1 Nummer 1 festgestellt, dass keine Antragsberechtigung vorliegt, wird der Antrag nicht weiterbearbeitet und die jeweiligen Antragstellenden unverzüglich über die Unzulässigkeit des Antrages informiert.

(4) Wird bei der Prüfung gemäß Absatz 1 Nummer 2 festgestellt, dass die Formvorschriften nicht oder nur teilweise erfüllt wurden, ist dies den jeweiligen Antragstellenden mitzuteilen und eine angemessene Frist zur Behebung der Mängel zu gewähren. Werden die Mängel bis zum Ablauf der Frist nicht behoben, ist der Antrag aus formellen Gründen abzulehnen und die jeweiligen Antragstellenden unverzüglich über die Ablehnung zu informieren.

=== § 9 Inhaltliche Prüfung
(1) Der GDA entscheidet einstimmig anhand des vorliegenden Antrags über die Darlehensgewährung und die Darlehensmodalitäten gemäß <<_12_rückzahlungsmodalitäten, § 12>>. Sieht er sich dazu nicht imstande, können weitere Nachweise von den Antragstellenden und ggf. deren Ehepartnern angefordert oder eine ergänzende Stellungnahme des Finanzreferates eingeholt werden.

(2) Das Darlehen kann gewährt werden, wenn

1. für die Vergabe die entsprechenden Haushaltstitel nicht erschöpft sind,
2. die Bedürftigkeit gegeben ist,
3. die Rückzahlungsmodalitäten vereinbart wurden und
4. es abzusehen ist, dass der Darlehensnehmende das Darlehen zurückzahlen kann.

(3) Die Gewährung eines Darlehens an ein Mitglied des Allgemeinen Studierendenausschusses bedarf zusätzlich der Zustimmung des HHA.

(4) Besteht Bedürftigkeit nach <<_10_bedürftigkeit, § 10 Absatz 1 Nummer 5>>, so darf das Einkommensverhältnis der mit der*dem Antragstellenden im Haushalt lebenden Person bei der Entscheidung des GDA nicht berücksichtigt werden.

=== § 10 Bedürftigkeit
(1) Bedürftigkeit im Sinne des <<_9_inhaltliche_prüfung, § 9 Absatz 2 Nummer 2>> besteht, wenn die jeweiligen Antragstellenden für einen absehbaren Zeitraum nicht in der Lage sind, den für die Aufrechterhaltung der Studierfähigkeit notwendigen Unterhalt zu bestreiten. Dazu gehören insbesondere:

1. Sozialbeitrag,
2. Miete und übliche Nebenkosten, sofern bei Nichtzahlung die Kündigung oder die Räumung droht,
3. Krankenkassen- und Pflegeversicherungsbeiträge, sofern bei Nichtzahlung ein Ausfall von Versicherungsleistungen droht, sowie
4. Studienentgelte oder Studiengebühren für weiterbildende Studiengänge gemäß https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=593995[§ 62 Absatz 5 Hochschulgesetz].
5. Kosten der Unterbringung in einer Schutzwohnung im Fall häuslicher Gewalt, <<_12_rückzahlungsmodalitäten, § 12 Absatz 3>> bleibt hiervon unberührt.

(2) Weitere Indizien für Bedürftigkeit im Sinne des <<_9_inhaltliche_prüfung, § 9 Absatz 2 Nummer 2>> bestehen, wenn die Antragstellenden

1. in den letzten 12 Monaten Eltern geworden sind,
2. aufgrund ihrer Abschlussarbeit ihrem Beruf nicht mehr nachgehen können oder
3. die Auszahlung der Gelder gemäß dem BAföG für einen unbestimmten Zeitraum nicht

erhalten, da die Bestätigung des Antrags noch aussteht.

(3) Besteht Bedürftigkeit im Sinne des Absatz 1 Nummer 1, sodass die Anlagen gemäß <<_7_anlagen, § 7 Nummer 2>> nicht vollständig zum Zeitpunkt des Antrags eingereicht werden können, wird das Darlehen vorläufig gewährt. Ein Anteil dieses Darlehens wird seitens des AStA für den Darlehensnehmenden an die Heinrich-Heine-Universität Düsseldorf überwiesen. Der Darlehensnehmende hat die Anlagen gemäß <<_7_anlagen, § 7 Nummer 2>> binnen 4 Wochen nachzureichen. Wird diese Frist nicht eingehalten, wird der bereits ausgezahlte Beitrag vom Darlehensnehmenden zurückgefordert und der restliche Beitrag des Darlehens nicht ausgezahlt.

=== § 11 Mitteilung über die Entscheidung
(1) Die Entscheidung des GDA ist den jeweiligen Antragstellenden unverzüglich mitzuteilen.

(2) Wird der Antrag genehmigt, ist den jeweiligen Antragstellenden der Abschluss eines Darlehensvertrages gemäß <<_13_inhalt_des_darlehensvertrages, § 13>> auf der Grundlage der Entscheidung anzubieten.

(3) Eine Ablehnung des Antrages ist zu begründen.

== IV. Vertragsgestaltung
=== § 12 Rückzahlungsmodalitäten
(1) Die Rückzahlungsmodalitäten werden auf Grundlage dieser Ordnung zwischen dem AStA und den jeweiligen Darlehensnehmenden in einem Darlehensvertrag vereinbart.

(2) Das Darlehen ist zinslos.

(3) Die Höhe des Darlehens darf 1.200 EUR für Bedürftige gemäß <<_10_bedürftigkeit, § 10 Absatz 2 Nummer 1>> nicht überschreiten. In allen anderen Fällen darf das Darlehen 600 EUR nicht überschreiten.

(4) Die Rückzahlung des ausgezahlten Darlehens muss spätestens 3 Monate nach der vollständigen Auszahlung beginnen.

(5) Die maximale Dauer der Rückzahlung des Darlehens darf 24 Monate nicht überschreiten.

(6) Besitzt der Antragsstellende keinen ständigen Wohnsitz innerhalb der Europäischen Union, ist der Rückzahlungszeitraum bis zum Ende der Aufenthaltsgenehmigung oder des Visums, höchstens jedoch auf 12 Monate zu begrenzen.

=== § 13 Inhalt des Darlehensvertrages
(1) Der Darlehensvertrag muss Angaben enthalten über

1. die Vertragsparteien,
2. die Höhe des Darlehens,
3. die Höhe der Rückzahlungsraten,
4. den Beginn des Rückzahlungszeitraums,
5. das Ende des Rückzahlungszeitraums und
6. die Bankverbindung der Studierendenschaft.

(2) Der Vertrag kann vorsehen, dass das Darlehen nicht in einer Summe, sondern in maximal sechs monatlichen Raten ausgezahlt wird.

(3) Der Vertrag kann vorsehen, dass die Darlehenssumme unmittelbar an die Gläubigerin oder den Gläubiger der jeweiligen Darlehensnehmenden ausgezahlt wird.

(4) Der dieser Darlehensordnung angehängte Musterdarlehensvertrag soll den Verträgen
zugrunde gelegt werden (Anlage 2).

(5) Der Darlehensvertrag ist vom Darlehensnehmenden und zwei AStA-Vorstandsmitgliedern zu unterzeichnen.

== V. Vertragsabwicklung
=== § 14 Verzug, Nichtzahlung
(1) Geraten Darlehensnehmende mit der Rückzahlung mehr als 14 Tage in Verzug, sind sie durch den AStA umgehend zu kontaktieren und an ihre Rückzahlungsverpflichtung zu erinnern, sowie auf die Möglichkeit eines Antrages auf Ratenminderung oder Stundung bei Rückzahlungsproblemen hinzuweisen. Die Kontaktaufnahme muss mindestens in Textform erfolgen, soll aber nach Möglichkeit auch auf anderem Wege (telefonisch) versucht werden. Da eine förmliche Zustellung gewährt sein muss, wird der AStA eine Adressermittlung durchführen, wenn die Darlehensnehmenden nicht anders zu erreichen sind.
(2) Bei andauerndem Zahlungsverzug trotz Kontaktversuch gemäß Absatz 1 sind durch den AStA folgende Schritte zu ergreifen: Die durch den Zahlungsverzug aufgelaufenen Raten, sowie die Restdarlehensschuld sind bei der Schuldnerin oder dem Schuldner in vollem Umfang anzumahnen. Die Rückzahlungsforderung wird ab Verzug der 2.Monatsrate sofort fällig. Ist die Mahnung erfolgt, ergreift der AStA die folgenden Schritte

1. Vereinbarung eines verbindlich neuen Rückzahlungsplans mit den Darlehensnehmenden. Hierbei sind insbesondere die wirtschaftlichen Verhältnisse des Antragsstellers neu zu bewerten. Der Abschluss des neuen Rückzahlungsplans bedarf der Zustimmung des HHA.
2. Ist 14 Tage nach der ersten Mahnung keine Rückmeldung von den Darlehensnehmenden beim AStA eingegangen, erfolgen zwei weitere Mahnungen mit einer Fristsetzung von 14 Tagen über die Gesamtschuld, in der auf die Einleitung von rechtlichen Schritten hingewiesen wird. Erfolgt weiterhin keine Rückmeldung, ist das gerichtliche Mahnverfahren ohne weitere Verzögerung einzuleiten.

(3) Das Verfahren nach Absatz 2 kann ausgesetzt werden, wenn

1. Anträge auf Ratenminderung oder Stundung von den jeweiligen Darlehensnehmenden vorliegen,
2. die Kosten der Einziehung voraussichtlich größer sind als die einzufordernde Darlehensschuld, oder
3. die Einziehung nach Lage des einzelnen Falles für die jeweiligen Darlehensnehmenden eine besondere Härte bedeuten würde.

(4) In Fällen der Aussetzung nach Absatz 3 Nummer 2 und 3 ist die Angelegenheit zur Entscheidung über eine Niederschlagung oder einen Erlass der Darlehensschuld gemäß § 16 Absatz 2 dem HHA vorzulegen.

(5) Die Kosten des Mahnverfahrens und des Zahlungsverzuges tragen die jeweiligen sich in Verzug befindlichen Darlehensnehmenden. Es werden keine Verzugszinsen erhoben. Die Kosten für die Adressermittlung tragen ebenfalls die Darlehensnehmenden.

=== § 15 Anträge auf Ratenminderung oder Stundung
(1) Auf begründeten Antrag der jeweiligen Darlehensnehmenden kann eine Ratenminderung oder eine Stundung gewährt werden.

(2) Die Höhe einer geminderten Rate liegt bei wenigstens 10 EUR im Monat.

(3) Eine Minderung wird in der Regel für 6 Monate gewährt, eine Stundung in der Regel für 3 Monate. Der vereinbarte Rückzahlungszeitraum darf durch Minderungen und Stundungen insgesamt höchstens um 12 Monate verlängert werden. Hiervon unberührt bleiben die Fristen gemäß <<_12_rückzahlungsmodalitäten, § 12 Absatz 5 und 6>>.

=== § 16 Entscheidungsbefugnisse
(1) Entscheidungen über Anträge auf Ratenminderung trifft das Sozialreferat die Schuldenund Budgetberatung des AStA.

(2) Entscheidungen über die Stundung, die Niederschlagung und den Erlass von Forderungen aus Darlehensverträgen trifft die Finanzreferentin oder der Finanzreferent nach Zustimmung des HHA. Entscheidungsgrundlage ist https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=8184&anw_nr=2&aufgehoben=N&det_id=557824[§ 20 Absatz 1 Haushalts- und WirtschaftsführungsVerordnung der Studierendenschaften NRW].

== VI. Schlussbestimmungen
=== § 17 Änderungen und Ergänzungen
Diese Ordnung kann durch das Studierendenparlament mit einer Mehrheit von zwei Dritteln der satzungsgemäßen Mitglieder geändert werden.