=== § 1 Erhebung von Beiträgen
(1) Von der Studierendenschaft der Heinrich-Heine-Universität Düsseldorf (im folgenden Studierendenschaft genannt) werden in jedem Semester gemäß https://recht.nrw.de/lmi/owa/br_bes_detail?sg=0&menu=0&bes_id=28364&anw_nr=2&aufgehoben=N&det_id=593989[§ 57 Absatz 1 des Gesetzes über die Hochschulen des Landes Nordrhein-Westfalen] sowie gemäß xref:satzung::index.adoc#_3_rechte_und_pflichten_der_studierenden[§ 3 Absatz 3] der Satzung der Studierendenschaft von allen immatrikulierten Studierenden der Heinrich-Heine-Universität Düsseldorf Beiträge erhoben.

(2) Die Beitragspflicht gilt auch für vom Studium beurlaubte Studierende.

(3) Die erhobenen Beiträge dienen der Erfüllung der Aufgaben der Studierendenschaft.

=== § 2 Fälligkeit der Beiträge
(1) Die Beiträge werden mit Einschreibung, Rückmeldung oder Beurlaubung fällig.

(2) Der Beitrag wird von der Heinrich-Heine-Universität Düsseldorf eingezogen.

=== § 3 Höhe der Beiträge
(1) Bei der Festsetzung der Beiträge sind die sozialen Verhältnisse der Studierenden angemessen zu berücksichtigen.

(2) Es werden folgende Beiträge je Studierender und je Semester erhoben:

1. Ein Beitrag von 104,28 Euro für das Semesterticket VRR im Sommersemester 2022.
2. Ein Beitrag von 29,25 Euro für das Semesterticket NRW im Sommersemester 2022.
3. 7,50 EUR als AStA-Beitrag; abweichend hiervon beträgt der AStA-Beitrag für das
Sommersemester 2022 6,00 EUR.
4. Ein Beitrag von 1,00 EUR als Fachschaftenbeitrag.
5. Ein Beitrag von 3,00 EUR als Beitrag für den gemeinsamen Hochschulsport der Düsseldorfer ASten.
6. Ein Beitrag von 1,50 € als Beitrag für das Hochschulradio.
7. Ein Beitrag von 0,35 € für die Rückerstattung der Kosten der Semestertickets VRR und NRW bei sozialer Bedürftigkeit gemäß   <<_4_rückerstattung_der_beiträge_für_das_semesterticket_vrr_und_semesterticket_nrw, § 4>>.
8. Ein Beitrag von 1,50 EUR für die Kooperation mit Nextbike.

(3) Die erhobenen Beiträge müssen im Haushaltsplan der Studierendenschaft separat ausgewiesen werden.

(4) Die im Sommersemester 2022 zu viel an den AStA überwiesene Beitragsmenge – bezogen auf die geänderten Beträge in <<_3_höhe_der_beiträge, §3 (1) 1. und §3 (1) 2.>> - wird an die Heinrich-Heine-Universität Düsseldorf zum Zwecke der Erstattung an die Studierenden zurücküberwiesen. Diese Regelung gilt nur für das Sommersemester 2022.

=== § 4 Rückerstattung der Beiträge für das Semesterticket VRR und Semesterticket NRW
(1) Bei sozialer Bedürftigkeit können die Beitrage für das Semesterticket VRR und das Semesterticket NRW zurückerstattet werden.

(2) Die Rückerstattung erfolgt auf Antrag, bei dem die soziale Bedürftigkeit durch die/den Antragstellende/n nachzuweisen ist. Des Weiteren müssen Name, Matrikelnummer und Anschrift der/des Antragstellenden im Antrag enthalten sein. Die Anträge müssen bis 150 Tage nach Semesterbeginn beim AStA-Sozialreferat eingereicht werden.

(3) Zwei Mitglieder des Sozialreferats und ein stellvertretendes AStA-Vorstandsmitglied bilden gemeinsam die Semesterticketkommission (STK) zur Bearbeitung der Anträge. Die genaue Benennung der einzelnen Personen erfolgt per Vorstandsbeschluss.

(4) Die Bewilligung oder Zurückweisung der Anträge erfolgt nach Prüfung ebendieser durch die STK. Eine Entscheidung über die Anträge hat bis zum Ende des Semesters zu erfolgen, in dem der Antrag gestellt wurde. Anträge, die aus den Gründen, die der/die Studierende nicht selbst verschuldet hat, nach Ablauf der Antragsfrist gestellt werden, können nachträglich bewilligt werden, wenn der Haushaltsausschuss hierzu einen Beschluss fasst. Die Angelegenheit ist auf einer nichtöffentlichen Sitzung zu beraten.

(5) Folgende Personengruppen sind besonders zu berücksichtigen:

1. Studierende mit einem oder mehreren Kindern,
2. Ausländische Studierende ohne Arbeitserlaubnis in der Bundesrepublik Deutschland, die darüber hinaus keine finanzielle Förderung, beispielsweise in Form eines Stipendiums, erhalten,
3. Studierende mit Behinderung oder chronischer Erkrankung.

(6) Nicht verausgabte Mittel werden in das nächste Semester übertragen. Sollten in einem Semester die aus vergangenen Semestern rückgestellten Mittel und die Mittel aus <<_3_höhe_der_beiträge, § 3 Abs. 2 Nummer 7>> zusammen nicht zur Erstattung aller bewilligten Semesterticketrückerstattungen ausreichen, so ist die Differenz aus dem AStA-Haushalt zu begleichen und für die nächste Änderung der Beitragsordnung in Form einer Anpassung des Beitrags nach <<_3_höhe_der_beiträge, § 3 Absatz 2 Nummer 7>> zu berücksichtigen.

(7) Auf eine Rückerstattung besteht kein Rechtsanspruch.

=== § 5 Änderung
Diese Ordnung kann durch das Studierendenparlament mit einer Mehrheit von zwei Dritteln der satzungsgemäßen Mitglieder geändert werden.